### ISSUE TITLE
Biting Keeki doesn't seem to take any effect

### ISSUE THREAD

**Issue by JupiterFive** [yogstation13/yogstation#1035]
Some time ago, when I tried to eat Keeki because I was starving, it said that I ate it but made a punch noise instead. I did this tons of times and my hunger didn't appear to go up.

**Comment by Cruix** [comment]
It gives you a very tiny amount of nutriment, 0.4 nutriment and 0.4 vitamin, per attack. For comparison, a 50 potency apple has 5 nutriment in it. It has to be small because the keeki takes 10 damage per bite and heals 8 per tick. If you had just waited and spaced your bites out to be about two seconds apart, you would have infinite food and a living keeki.

But you just couldn't wait.

You monster.

**Comment by 00aquir** [comment]
you mean Cak? Cak is love. Cak is yum.
