### ISSUE TITLE
Rebase to recent TG code?

### ISSUE THREAD

**Issue by JupiterFive** [yogstation13/yogstation#1040]
A while back, we did rebase, but /tg/station changed a lot lately. One example is that the ID cards changed, another being that the paper bins and drawers have new appearances, and yet another that's more noticeable is that Medibots have sounds.
It's just a suggestion, could be a change for the better.

**Comment by oisin100** [comment]
"small" isnt a word that can be applied to this...

**Comment by JupiterFive** [comment]
Just realized that, gonna change the title.

**Comment by X-TheDark** [comment]
We might have better luck porting/rebasing certain features than trying to keep everything up to date.

/tg/station will always be far, FAR ahead of what we can be.

**Comment by Time-Green** [comment]
Do you have any idea how horrible it is to rebase?

**Comment by AdamElTablawy** [comment]
@X-TheDark that's what we said last time

if we want to remain a relevant server in terms of features we need to consistently port all of /tg/'s pr's

which is simple in general for people who aren't me since they can make multi-file pr's where i can't

**Comment by ShadowDeath6** [comment]
>ID card rework
sprite changes
added sounds

ah yes that's a lot of important things that are absolutely necessary

**Comment by Super3222** [comment]
There are three honest pathways. Since this hasn't been mentioned before I'll just inform everyone here. 

1 - We continue with how we're doing things. Just making our changes and additions, better or worse, on whatever /tg/ build we have. If we /really/ want something from tg, than we port it and give credit.
2 - We somehow convince Cruix and/or XtheDark to rebase every week. Please note, rebasing is not easy. Especially when we're at the state we're at right now. It's either a head coder manages to rebase all of those commits from /tg/ or we somehow commit all of our features and tweaks a second time. But that's just me, lots of other coders I'm sure can tell you otherwise.
3 - We stop using this repo. Yogstation bluntly use /tg/'s code for the server, and you can guess what happens next.

Obviously we've taken ~~Objective Apples~~ road 1 after the rebase. It's really up to the (council) Head Coders to decide. In this situation we're in between a rock and a hard place.

inb4 baw, the ambasador, re-appears

**Comment by vladlds** [comment]
@JupiterFive , can you please link ID card rework commit/branch?

**Comment by JupiterFive** [comment]
I haven't made one yet.
