### ISSUE TITLE
Chief Engineer Deputy ((Suggestion))

### ISSUE THREAD

**Issue by Skyguy345** [yogstation13/yogstation#1046]
Hello, my name is Skye (Skyguy345), Noel Edwards on Yogstation 13. I normally play as the Chief Engineer, or an Engineer, and I noticed that most of the Engineers set up the tesla / sing, steal a space suit, then go off to the white ship.
I wish to organize this.
I would like to suggest a new position. If the Chief Engineer had an assistant, someone that had access to all of Engineering and Atmos (Except, perhaps, the CE's office), he/she could assist the CE in maintaining order and attempting to organize any necessary repair runs on the station.

PROS: Would help maintain order in Engineering, would make the station more likely to be repaired, would help to enforce the rule of not running off with the Hardsuits.

CONS: Would increase the difficulty of being a Traitor in Engineering, as the CE and his "Deputy" would try to locate you far more often for repairs and the like. May make Rev round harder as the CE, if your trusty assistant engineer is converted.

NOTE: This "Deputy" doesn't necessarily need an office, or be implanted with a loyalty implant. He wouldn't qualify as a head, as he's merely the CE's personal assistant engineer.
Thank you for taking the time to read this,
~Skye

**Comment by Alek2ander** [comment]
>most of the Engineers set up the tesla / sing, steal a space suit, then go off to the white ship.

The Deputy Chief Engineer will set up the tesla / sing, steal a space suit, then go off to the white ship.

**Comment by Time-Green** [comment]
If they take the engi-suit for their own gain, ahelp it.

**Comment by vladlds** [comment]
As a head, you are the one who is supposed to keep the department going. You are in charge of all equipment as well.
Consider doing your job and coordinate with security in case someone is failing theirs.

From space law:
Insubordination - To disobey a lawful direct order from one's superior officer. Charge issued by a head of staff to one of their direct subordinates. The person is usually demoted instead of incarcerated. Security is expected to assist the head in carrying out the demotion.

Dereliction of Duty - To willfully abandon an obligation that is critical to the station's continued operation. A demotion is often included in the sentence. Emphasis on the word critical: An officer taking a break is not dereliction in of itself. An officer taking a break knowing that operatives are shooting up the Captain is. Engineers who do not secure a power source at the start of the shift and heads of staff who abandon the station can also be charged.

From server rules:
3.1.2: Hardsuits are for work. Do not take a hardsuit unless you have work to do that requires it. Avoid wearing hardsuits inside the station when there are no emergencies.

**Comment by Skyguy345** [comment]
Hello, it's me again.
So, I fully understand Space Law about insubordination, as well as the server rules. Unfortunately, it appears when I'm on more and more often, Security won't answer (I would guess because they're dead), and there are no admins online. Perhaps another option would be to allow the CE to promote one of his dedicated Engineers using his department console - Give him a proper role and title that he can assign to his "Deputy".
 I understand that what I suggested for the CE's personal Engineer assistant, or "Deputy", will be helping the CE with his job. One of the reasons I suggested this is fewer and fewer Engineers seem to coordinate with him. I have had entire shifts where all the Engineers disappear before the Engine is set up (No, they were not traitors, they only refused to return). And if everyone leaves Engineering, even if they're fired, who will maintain the station? The CE himself? And if they are banned? The reason I suggest this is to make it possible to enforce the rules in-game in a, hopefully, fun way; without job-bans, gibbing, or making the Engineer the least desirable job.
Thank you for reading this,
~Skye

**Comment by JupiterFive** [comment]
I'd probably suggest adding the head's assistant idea to all other heads of staff.

**Comment by Drakkon** [comment]
This is why I'd suggest access consoles for each big department (engineering, medical, science, & security) similar to the HoP's, except it can only assign/change access within the confines of that department. This would still require the HoP's computer to assign etc. (service) access and put less pressure on them if they weren't there (or just incompetent).

**Comment by Cruix** [comment]
That already exists almost exactly as you described it. All heads have a console that they can use to demote anyone to assistant or give them any access in their department.

**Comment by Drakkon** [comment]
ew wat? In what ways are they not like I described then?
If they're literally exactly how I described, permission for honorable suicide.
