### ISSUE TITLE
Make emag amount of uses limited and chargeable

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#1087]
Emag should use energy and be rechargeable instead of unlimited use.

**Comment by Super3222** [comment]
This is a joke, right.

**Comment by ShadowDeath6** [comment]
??????

**Comment by X-TheDark** [comment]
I support this at least for a time-limited test. The versatility and usefulness of e-mags should not be taken for granted and should not be used as a reason to NOT add some sort of drawback to them.

"But it's emag, it obviously should stay unchanged, given how useful it is" should not be valid grounds to dismiss this idea.

**Comment by Drakkon** [comment]
Rechargeable like a staff/adv. gun over time? I'd be okay with that.

**Comment by Ephemeralis** [comment]
I like it. Have it leave a trail by destroying APCs/rechargers to recharge.

**Comment by aphielanis** [comment]
The more times a traitor uses their cryptographic sequencer the more likely they are to get caught, that's been my experience anyways.

**Comment by vladlds** [comment]
@Super3222
> Yeah, no. I liked his LAWSET idea, but anything as permanent is bad. Let's get that clear.

**Comment by Super3222** [comment]
@vladlds 

Yes. Permanent un-convertible law sets are bad, and they go against the basic mechanics of silicons. How is that relevant?

I don't know how people are taking emags for granted. Any idiot emagging a bunch of random doors is bound to get caught, and if he doesn't than it's left up to the Detective to catch him.

And down the road, you're either going to do 2 things with this change. 1) Make it so the emag juice is very limited, and small. So they can maybe emag up to 10~ things, and have to go through a cooldown. 2) Make it so emag has a medium-large limit, which will probably never be reached because people don't ALWAYS have to use an emag.

In theory, it may sound great. But in the actual game? Why the fuck would I need to emag open 20 different doors?

In any case if this pulls through, nuclear operatives better get an infinite one because they NEED IT.

**Comment by ShadowDeath6** [comment]
>emag being required for ops

:triumph: heated

**Comment by Super3222** [comment]
Well I mean, not from the get go. Never from the get-go imo. But the ones they buy being infinite. There are reasons for it

**Comment by AdamElTablawy** [comment]
Nope. Not happening.

It's been tried on other servers and fails badly.
