### ISSUE TITLE
free mining ship has forced atmos tiles 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11536]
## Test Merges: 
Not Supplied / None
## Reproduction:
When I was a free miner cap, I had gone to the station due to a crew member needing advance medical aid. While there a meteor event triggered, and one hit the ship. Something interesting though.... it wasn’t spaced. I had my hard suit off, and no objects were being pulled. This was near the center of the ship, so it wasn’t atmos fans either.
 Submitted by: PhoenixFox (356215755504746496)

**Comment by patpol4** [comment]
This is probably related to monstermos sometimes not updating on wall deletion

**Comment by UselessTheremin** [comment]
yeah, probably due to atmos lag and spaghetti code, but there is no supplied round id ( and when i talked to the author on the discord this was apparently quite a while ago ) so i think im just gonna go ahead and close this because its not something that we can just fix if there is no other supplied information.
