### ISSUE TITLE
Buff Blobs 

### ISSUE THREAD

**Issue by Paroclomas** [yogstation13/yogstation#1174]
I just played with the new blobs(i dont know how new the last time i played was like months ago) they nerfed them too much. now its literally impossible for a blob to win. Like, theres no way no fucking way.

Before the nerfing, the blob was op, true, but that was the point of it. The idea was that it was a difficult opponent, one that required the crew to coordinate their attacks. And sometimes, the crew won, it was rare but not impossible.

But now its just pointless, I say either revert to the old blob or remove blob completely, keeping it like this makes no sense IMO

**Comment by drderp3635** [comment]
the blobs we faught died so fast because everyone had weapons from previous blobs and had no time to spread as a result

**Comment by X-TheDark** [comment]
Any more details on what makes the blob bad?

* Is it flashbangs/bombs?
* Are the lasers too good?
* Does it autospread/get points too slowly?
* etc

**Comment by Paroclomas** [comment]
Its all of it, the general balance. IMO the little blobs have way to little hitpoints. The different types of blob dont mean shit, they dont give any advantage. Blobbernauts were nerfed to shit, an assistant with a broken bottle is more dangerous than a blobbernaut, they have not much hitpoints, heal too slowly on the blob, are slow and dont hit for shit. The autospread and points are slow too. And dont even get me started on emmiters.

Of course that fixing all of this at the same time would make it insanely op, so it should be some of them.

I think the idea of blob is that it SHOULD be A LITTLE op, in the sense that it is almost impossible to kill by a couple of guys or an uncoordinated mob, but possible for an organized station. This was accomplished by the previous blob, it really was, most of the times the blob won but sometimes particularly good crews won against the blob and it was great because it was an accomplishment.

Nowadays theres like, no way the blob can win. 3 guys with welders can take any blob out, even if it had a few moments to spread.

**Comment by darkwahn** [comment]
We could just remove the game mode since it's terrible and never in a good place balance wise.

**Comment by Paroclomas** [comment]
I agree. Personally i think the game mode as it was originally was great and fun, both as blob and as crewmember. But if people dont like it (ahem, cant handle it) then remove it, nerfing it is pointless. IMO either bring back old blob or remove blob but current blob is not good.

**Comment by Super3222** [comment]
You bring up some good points, and it's nice to hear player feedback on this issue. Blob was nerfed a few weeks (or even a month) ago because the crew only rarely won, and the blob would most likely win all the time.

Little blobs have 4 melee, and blobbernauts deal 20 brute damage.

I don't know if removing the game mode is the best option. It'd be like removing wizard - which isn't for everyone, isn't fun for anyone but the wizard, and the crew will only have the quarter of a chance to beat if the wizard knows what they're doing. That's the same situation that I feel blobs are facing. They're strong antagonists that not everyone's going to win against, but if you hit them from their weakpoints you'll win.

So yes, buffing blobs - basically undoing some of Adam's harsh nerfing - seems like the appropriate action.

**Comment by X-TheDark** [comment]
I'm pretty sure current blob is basically /tg/ minus a few minor cost/chem changes.

**Comment by Paroclomas** [comment]
Are you sure?, from what i saw it was very changed. Have you ever seen a post-nerf blob win? i havent.

with the old blob i have no problem running against a full crew. Against the NEW blob i can guarantee that me and another person(maaaybe 3) with welders can take it down

**Comment by ShadowDeath6** [comment]
Blobs currently take double damage from burn, so normal blobs are instakilled by almost anything. The problem is that welders do so much fucking damage that three assistants with welders can solo a blob or at least make it waste a massive amount of BP trying to fight back against them. It was a bad decision making a 1v30 antag have the disadvantage.

**Comment by AdamElTablawy** [comment]
I nerfed the shit out of blob.

This is intentional and I am against any buffs. Blob is a cancer gamemode that the crew never won. It scaled unfairly. Past the first node, unless you had xrays, the blob would win because it produced blobs just that rapidly and any damage you do to it is temporary.

As it is now, blob is instantly killed by welders unless it's a special blob type. It takes double damage from burn and standard damage from brute, and it's resource regen and blob production is massively slowed down.

**Comment by Paroclomas** [comment]
yeah adam we all get its been nerfed to death. What im saying is that it should be either completely removed or brought back to its former glory. Some people liked the way it was, i dont think anyone enjoys it the way it currently is. I think there should be a vote in the community to take a real decision.
