### ISSUE TITLE
Cannabis has lipolicide and space drugs in it not THC

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1184]
This major oversight makes cannabis toxic and retarded. THC is organic, safe, and has no toxins in it.
 Also as a side note for some reason it says leaf, it's not tobacco. Botanists are harvesting the buds.

**Comment by ShadowDeath6** [comment]
pretty sure space drugs do brain and toxin damage

**Comment by ShadowDeath6** [comment]
weed kills, kids, don't play 2d spaceman stoner and you won't OD on space drugs

**Comment by aphielanis** [comment]
No it doesn't. Some kids with cancer take a concentrated form of cannabis called a dab that's as potent as 20 cannabis cigarettes and it actually helps them feel better. None of them have ever been "killed by weed" either.
 Alcohol is  more dangerous and a lot more toxic.

**Comment by drderp3635** [comment]
Seems like a "get the fuck over it" kind of problem. You can grow tomatoes that make people teleport but "my weed isn't realistic enough" is your problem with the realism.

**Comment by Ephemeralis** [comment]
This is by far the dumbest issue I have ever had the misfortune of reading.

Go fucking read the Hydroponics wiki page on /tg/ for more than 10 seconds and actually try playing Botanist in a round once instead of clogging up this repo with these utterly asinine issues that consist of **I DON'T ACTUALLY KNOW HOW TO PLAY THE GAME PROPERLY PLEASE FIX**
