### ISSUE TITLE
Can we get a better UI for chameleon gear?

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1199]
Right now finding a specific torso or helmet is extremely annoying. Scrolling through that huge ass list is ridiculous, and looking for the first letter takes just as long. If we could CTRL F search the list it wouldnt be so bad. Can we get a better UI that lets us search like the syndicate PDA or sec records?

**Comment by Stealthkibbler** [comment]
You can just type the desired beginner letter can you not? Same with security cameras etc.

**Comment by puremanbird** [comment]
yeah, but theres 50 different things that start with S. I even addressed that in my post.

**Comment by Cruix** [comment]
Working on it

**Comment by Cruix** [comment]
I've changed chameleon items so that instead of each one giving you an action button, wearing or holding any chameleon items will give you a single button that opens a customization menu. The UI needs work, but it's all functioning properly.

UI so far:
![cham](https://cloud.githubusercontent.com/assets/16478175/20243749/5b2204ea-a92a-11e6-9986-922a9d76d11c.png)

![cham2](https://cloud.githubusercontent.com/assets/16478175/20243750/5f51b6c8-a92a-11e6-8dd3-76130fab3b83.png)

You can change the items individually in the upper right or you can select a job preset and hit "update" to set all the chameleon items you are currently wearing to that job's default version. The UI isn't great right now, so how should I improve it?

**Comment by ShadowDeath6** [comment]
you can improve it by merging it now :^)

**Comment by Drakkon** [comment]
<_< NOICE. All selections should look this nice if it's easy (and possible). 
Example: Donor hat selection
