### ISSUE TITLE
Remove AI's universal transceiver.

### ISSUE THREAD

**Issue by Jc1469** [yogstation13/yogstation#1243]
Basically, NTSL doesn't really do much these days, other than the occasional person using it to mute stuff because they can't be bothered flipping an APC off.
If we did this, the AI would be back to only starting with AI Private and Common, so people would be **encouraged to** _and by that I mean better fucking_ use NTSL to view other channels, or even just view the machinery to find the frequencies for the channels they wish to observe.  And hey, NTSL is fun.  

It's a learning experience.

**Comment by Alek2ander** [comment]
NTSL is for honk scripts, muting, and other giggles that are ultimately pointless (except for traitors). Since seeing all channels is too useful, removing the universal transceiver will just split the AI players into those that lose out on a feature and those that copy-paste the same script every round. This will bring back the fiddly inconvenient AI radio without channel colors, standard channel codes, jumping to core to switch around intercoms, etc.

**Comment by Jc1469** [comment]
Sounds great.  Let's just remove NTSL then. The only real use it had was allowing the AI to view all the channels.  And $source=$source + "{ " + $job + "}";  but that's still used by one person today, so I guess that's good, right?  
Or even add job indicators by default, why the heck not?

**Comment by aphielanis** [comment]
AI is one of the most complicated intimidating jobs. I would rather have features that make a newbie experience with AI accessible rather than more complicated please?

**Comment by Jc1469** [comment]
Not sure I'd call hearing every radio channel very newbie friendly. On top of seeing alarms, alerts, borg talk. 

The AI's chat is always going to be a mess.    I still think they should just learn the frequencies and only use the channels that are important.  Or make an extremely messy script $broadcasting every channel to one channel.  Though, when I tried that last, it didn't work anymore.

**Comment by matskuman5** [comment]
How about we add a signal tech job?

#1195 

That way people don't get intimated playing as AI but NTSL isn't useless!

**Comment by ShadowDeath6** [comment]
forcing a player to copypaste scripts into some dumbass console so they can actually play an immobile slave job is a fucking dumb idea and this is a stupid feature request :-1:

We might as well make every job require NTSL to be set up by the AI because it's a learning experience and you should have to know how to do it to experience the game

**Comment by Alek2ander** [comment]
Let's make every round start with all telecoms equipment shut down and unlinked. That's got to be !!FUN!! for everyone.

**Comment by Jc1469** [comment]
I agree. 

Let's do it.  

Let's go boys.
