### ISSUE TITLE
2 New Lavaland Structures

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1253]
Here ya go? Never dealt with uploading DreamMaker things, so bear with me please. If it's shitty and/or you higher ups want me to change something, say.
[Lavaland Structures (Crazy_Drakkon).zip](https://github.com/yogstation13/yogstation/files/604588/Lavaland.Structures.Crazy_Drakkon.zip)
![lavaland structure - cafe of broken dreams](https://cloud.githubusercontent.com/assets/18729830/20497372/874611f4-afee-11e6-8341-0461299993a7.png)
![lavaland structure - gas station](https://cloud.githubusercontent.com/assets/18729830/20497373/8749bd90-afee-11e6-9dc9-dcd31be9e4d8.png)

**Comment by Time-Green** [comment]
Can you give us pictures instead? I am not very keen on downloading stuff from the internet.

**Comment by Drakkon** [comment]
Makes sense. Edited.

**Comment by Super3222** [comment]
For the first one add some goliaths, weavers, or watchers to it please. Otherwise it's just taking a lot of space for almost no reason.

The second. Too much oxygen tanks is a bad thing. But I can see this place being a haven for prisoners so eh. I'd suggest removing at least 3 of those canister storages on the outside.

**Comment by Super3222** [comment]
Also where do those stairs lead?

**Comment by Stealthkibbler** [comment]
First one is very empty and I'd suggest removing the ladders unless they actually lead somewhere, the gas station one looks amazing though but with the sink you should move it so it looks like its up against the wall, you can do this by right clicking on the sink, hitting edit and there will be pixel_x and Pixel_y, you want to use pixel_y, change that value in the positive range until the sink doesn't look like its just sitting in the middle of the tile. I'd also suggest replacing the single donut with a box of donuts as donuts have a lot of sugar and can be eaten in 1-2 bites.

**Comment by Stealthkibbler** [comment]
Gas station also has lights on the outside but none on the inside, add some lights on the inside as it would complete the aesthetic tough to the fact it already has lights on the outside.

**Comment by Drakkon** [comment]
@Super3222 @Stealthkibbler Reference to Fallout 1/2 actual map design, but I can remove it.

**Comment by Drakkon** [comment]
@Super3222 I'll add a bunch of reg lavaland mobs instead of winging it with vaguely Fallout-related mobs?

**Comment by Stealthkibbler** [comment]
The streets are rather dull and boring, you could try livening them up with more junk, misc objects or a skeletal corpse or two here and there. the skeleton corpses are /obj/effect/mob_spawn/human/skeleton, while 'remains' are /obj/effect/decal/remains/human. indoors could use a couple remains. You could also add some blood splatters /obj/effect/decal/cleanable/blood the 'old' type would probably fit in with your fallout ruin. 

Also since you're making it fallout themed you'll want to use /obj/effect/decal/cleanable/greenglow which looks a lot like stained radioactive waste. Maybe add in some /obj/item/weapon/broken_bottle.

All I have to left to say is to experiment with the item trees more and dig around for anything you believe would be suitable loot or that would just complement the ruin itself; you generally want large ruins to have something nice, since its a casino maybe include a vault with a lot of space cash? Space cash is, believe it or not, very valuable in large quantities as cargo can ship it for points on a 1:1 conversion rate. Ontop of decals, loot etc, try to see if you can add in anyway to convey a self told story, maybe just from adding in a corpse or an array of items arranged in a specific way, you can even put in journals or notes by spawning in /obj/item/weapon/paper , then by editing it and putting text in the 'info' variable and if you want it labelled, by editing the "name" variable.

**Comment by Super3222** [comment]
@Drakkon Are you still working on this? If so message me on discord, and I can help you set up a PR.
