### ISSUE TITLE
Borer body bug

### ISSUE THREAD

**Issue by Trojanplunder** [yogstation13/yogstation#1273]
My host managed to get stuck in a wall during the random wormhole event. He went braindead and I tried to leave the body. Somehow I ended up out of the body but also "inside" the body still, able to inject chems and assume control. Whenever I assumed control, my borer body became a simple mob borer. Whenever I released control, I jumped back into that borer body wherever I left it. Dunno how reproduce-able this is, but it was certainly an interesting bug. 

I have some screenshots but I dont think they'd be too useful.

**Comment by AlpacaGoesCrazy** [comment]
My host was transformed into a slime with wizard powers. After this my camera broke  staying in the spot of transformation but i could run around as a borer. After relogging camera fixed and i could run around but i could not infect anyone because the game thoughr i was still in a host. Releasing didnt do anything, couldnt test it further because my ex-host who became slime killed me :(

**Comment by AdamElTablawy** [comment]
this is fixed
