### ISSUE TITLE
3 potential pai related bugs

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13168]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I've been playing pAI a lot recently and having fun, but theres been a few unexpected behaviors I've encountered the last couple days. 
Firstly, when i was in someones inventory as a pAI and the host was gibbed by a Space Carp Dragon, i was seemingly destroyed, or was atleast ghosted out of the pai (wasn't really able to check and didn't think to resubmit myself to check the pai was still there).
Second, when a pAI is emped, and they end up suffering from communication related issues, the vocal damage lasts for the entire rest of the round, which doesn't seem intentional (the damage can even stack as well if the pai is emped more than once, though that part does make sense).
Third, pAIs don't seem to be able to receive pda messages even if they download the digital messenger that lets them send pda messages (most evident when i began communicating to my bound master through pda in response to the previous vocal damage bug, and the 'pain' i was roleplaying it as causing).
Sorry if this report is a little long winded, but i suppose that's what happens when you report 3 bugs at the same time
 Submitted by: ☾ MidnightZero ☽ (525377778246484013)

**Comment by Oblisk234** [comment]
1: Gibbed self with pAI in bag, pAI was unaffected. Going to guess [ex_act](https://github.com/yogstation13/Yogstation/blob/79772067dc9ec5f15a25d2245291925b31a6a707/code/modules/mob/living/silicon/pai/pai_defense.dm#L30) was called and pAI got unlucky.
2: Intentional, see [emp_act](https://github.com/yogstation13/Yogstation/blob/79772067dc9ec5f15a25d2245291925b31a6a707/code/modules/mob/living/silicon/pai/pai_defense.dm#L5). Damage can be reversed by making a ricebowl and putting the pAI in it for 10 seconds.
3: Fixed by #22671 since pAIs used to use old PDA messaging.
