### ISSUE TITLE
Accents Interfere with Voice of God

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#13414]
### Severity

Inconvenience

### Short Description

accents interfere with voice of god

### Reproduction

spawn with accent
get voice of god
try to use commands
fail because accents change your speech pattern and makes specific commands impossible to say properly and get the effect off
cry

During my round, I chose heavy french.

### Round ID

39968

### Test Merges

#13033 #12948 #12912 #12959 #13185 

### BYOND Username

TheBombMaker

**Comment by Altoids1** [comment]
This is a bit annoying to fix, since using ``".x"`` to trigger the Voice of God is handled by your ``vocal_cords``, which receive the version of your message *after* it has been processed by the accent after the ``COMSIG_MOB_SAY`` signal has been passed to everything.

Just moving it to before the accent doesn't work, since that'd let you use .x at any time to bypass your accent, even when you have normal vocal cords.
