### ISSUE TITLE
TURN OFF RANDOM XENO EVENT FOR THE LOVE OF GOD

### ISSUE THREAD

**Issue by penguinfisher** [yogstation13/yogstation#1352]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Super3222** [comment]
???????????????????????????

**Comment by MasterPenguin5** [comment]
Xenos now spawn in literally every round about every 10 minutes. Send help.

**Comment by ShadowDeath6** [comment]
luh?

They should only spawn in an hour

**Comment by penguinfisher** [comment]
Maybe we should raise the cap to 1hr 30mins instead. The past 3 or 4 rounds in a row have all turned into a xenoshitfest.

**Comment by MasterPenguin5** [comment]
Alright I may have exaggerated the 10 minutes but, but still, even an hour seems too short considering xenos can quickly and effectively wreck the round for everyone else. Between last night and today I can count at least 5 rounds where xenos attacked the station and ruined it for anyone else who might have been having a successful round otherwise. Also no matter what the timer is, it feels like the event occurs much too frequently. I've literally seen more xeno rounds in the past 24 hours than I have in the past 6 months prior, and xeno rounds are already infamous for being essentially green-blooded deathsquads.

**Comment by ShadowDeath6** [comment]
Problem is not the timer, but the event weight

**Comment by Time-Green** [comment]
Weight for xeno is 3
To put that into perspective:
The light overload event is 40
And the anomaly event is 5 for every individual anomoly.

**Comment by ShadowDeath6** [comment]
swarmer is 1 I think

**Comment by matskuman5** [comment]
Higher weights are more likely to be picked than lower ones.

10 is default, 20 is twice more likely, 5 is half as likely

Meaning time is wrong

**Comment by ShadowDeath6** [comment]
yeah mats so it should be lower weight

**Comment by matskuman5** [comment]
I suppose it could be changed to 1 or 2

**Comment by Time-Green** [comment]
How am I wrong?
I read that up straight from the code and took some examples to put it into perspective.

**Comment by matskuman5** [comment]
I thought you had meant that the lights event was super high = rare
compared to the much more devastating xeno, sorry

7.12.2016 23.59 "Timato" <notifications@github.com> kirjoitti:

**Comment by Time-Green** [comment]
Ah ok. I thought I missed something. Sorry.

**Comment by Super3222** [comment]
For the past 5 months, alien infestation, along with other events, has a feature which increases their weight by 1 at every **half-hour** if the event controller decides to pick that event. Given that the event controller picks events every random 10 or so minutes. So by an hour it would most likely have a weight of 5.

But I've even noticed that it's more up to a random chance. I've seen a round where the event had maybe a weight of only 3 by an entire hour.

**Comment by Dragonforcefive** [comment]
This does sound annoying. Though I don't think that weight is the problem. And generally if the round is lasting a long time, then I understand why Xeno would be randomly chosen.
