### ISSUE TITLE
 PML-9 descript incorrect

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13586]
## Test Merges: 
Not Supplied / None
## Reproduction:
PML-9 says it comes preloaded. It does not come preloaded. I was scammed.

 Submitted by: Maxim (181876893178527744)

**Comment by Altoids1** [comment]
The issue is that the rocket launcher code is a massive hack at the moment. It poorly overrides the behaviour of ``/obj/item/gun/ballistic``, such that left-clicking at all with the launcher, even if it doesn't fire a shot, actually consumes a round unconditionally.

It does come preloaded; it's just that the round can poof out of existence if you sneeze on the rocket launcher wrong.

**Comment by Oblisk234** [comment]
PML-9 does come preloaded, per what has been previously said here.
