### ISSUE TITLE
 Shadowlings leaving z-level ends round

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13605]
## Test Merges: 
Not Supplied / None
## Reproduction:
If all shadowlings enter a bluespace locker (Or I assume leave the z-level) it will end the round prematurely.

 Submitted by: Cowbot (97736956326207488)

**Comment by Altoids1** [comment]
Making this not happen is slightly complicated since there's actually not a proper signal or component system for handling something like this. The nuke disk's `/datum/component/stationlover` thing doesn't *exactly* match up since the sling shouldn't really be able to, say, yeet into space repeatedly in order to teleport to arbitrary places on the station. I had a go at using `COMSIG_MOVABLE_PRE_MOVE` but that didn't really work either.

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
