### ISSUE TITLE
Ashwalker feedback for Super3222

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/yogstation#1396]
Great update for the Ashwalkers. I have gotten some good playtime with the ashwalkers since your recent update (4 shifts), so I will give my feedback, and little tweaks/changes that go along with what you were intending to do. 

I really like the idea of having a chieftain, but the ashwalkers rely too much on him for how he's currently implemented. This when executed properly is really fun gameplay (happened once out of my four shifts), but there needs to be some sort of system in place where you can control who is chief. In three of my four games, the chief just decided to not co-operate (just doing their own thing,  not communicating etc), go afk etc. It would be really nice if there was some sort of voting system for becoming the chief. The person that was voted into becoming the chief would then have to make his transformation AT the nest (to prevent abuse such as switching around chief-hood to use consoles). Becoming chief could have a longer cooldown this way (instead of just the 30 seconds), to make the changes meaningful (somewhere around the 6 minute mark).  The problem isn't getting the chief, it's that the players normally receiving the role do not want to lead the tribe in the first place, crippling it completely now that the members can not use technology and communicate.

Now here is a change that you might not have intended for the ashwalkers to have. Some sort of communication. This form of upgraded communication HAS to be a form of upgrade, not a given. An example of what I mean is that the chieftain could for example be able to acquire headsets (from miners, stealing them etc) , and using his increased intellect (and maybe some tools), he can convert headsets (or the station bounces radios) into their own frequency WITHOUT broadcasting it to the station (turning them short range) or being able to intercept it from the station (because of the lack of distance). This means that the communication would stay on lavaland. BUT there could be an ever bigger down-side, like being one way. The chief knows how to push the button to broadcast his message, but the ashwalkers don't need to do anything to listen (because the headsets are strapped to their ears. The regular ashwalkers would think that the chief is communicating telepathically. Since the radio's and headsets have been tampered with, you can also add a down-side like a little studdering here and there replacing 1/8th of the message with ***^%^#** . 

I'll post more idea's if I have any, but those were the two major ones. Thank you for reading this post.

**Comment by Hopekz** [comment]
Unrelated to Ashwalkers, Headsets that you could make should have the ability to disable common chat. This would be good for golem players that just want to use the headsets to communicate with each other on their own frequency without getting flooded by common.

**Comment by Cruix** [comment]
You can do that by changing the frequency on the headset.

**Comment by Hopekz** [comment]
"You can do that by changing the frequency on the headset."
The down side of that would be actually being heard by the A.I , Plus you do not block our common by changing the channels.

**Comment by Super3222** [comment]
I'll give your ideas some thought, and put them together with my follow up PR for that update. I can see where the problem lies with uncooperative chieftains. The tribe's progression does rely on the chieftain, so only a truly dedicated ashwalker should be able to take it's spot. Thank you for leaving feedback. I appreciate it.

As for communication I have a more pre-planned primitive idea for that, but it'd be in fewer numbers than re-engineered headsets. I'll give you a hint: blowing horns.

**Comment by AdamElTablawy** [comment]
super pls if you're gonna suggest something bounce it off me first since i'm the one who gave you the idea

**Comment by Hopekz** [comment]
Making a fireplace/campfire would be nice to not rely on cooking your food in lava. The furnace could be heated by plasma or anything else that you can think of.

**Comment by Hopekz** [comment]
It would also be a good feature if the ashwalkers could actually cover their armor in ash to make it blend it more with their surroundings and break up the lines, but not by much. This would give the ashwalkers that extra split second that they might need to surprise their target (also it just looks cool...so that's a good enough reason). Here is a rough version that I made..  the re-sprites suck because they were made quickly for presentation http://imgur.com/a/Qk1Lu

**Comment by Hopekz** [comment]
Also, one FINAL thought. Make the sacrifice spawning spike build able for the ashwalkers. Ashwalker bases inside ruins has always been something that seemed like it would be a really cool idea. But only implement this change AFTER your longer distance communication solution, so FOB's would be able to talk to each other. This change also encourages supply chains, a whole new level of depth for the ash walkers. Make it so that the spawning spikes could only be placed indoors to prevent them for randomly being out in the open, and you have interesting scenario's, like the Ashwalkers trying to take the mining base to themselves in a territory war, with the station being forced to respond/ maybe try to cut them off from the station.

**Comment by Dagdammit** [comment]
I'd still suggest ash walkers be able to communicate during ash storms, because the winds carry their voices to each other.

**Comment by Super3222** [comment]
That'd make communication really unpredictable and inconsistent. It sounds nice, but wouldn't be all that great in the game.

**Comment by Super3222** [comment]
@Hopekz 

After playing a few rounds as an ashwalker, I began to realize that making a voting round for that type of thing is... weird.

I think it was just the current time of the feature. Not too many people were up and ready to go and lead because they weren't into it yet. Lately, I've been seeing some pretty great chieftains lead their clan to victory and such.

I think leaving it up to the ghost is a good idea. If you have a bad chieftain who refuses to lead, kill them and throw them into the pit.

I am going to outline some things like communication, and clear up some bugs with the tendril.

As for buildable tendrils, the idea was going to be that the chieftain could convert other tendrils into nercopolis ones. Not so sure about that now to be honest with you.

**Comment by Dagdammit** [comment]
I just had my first round where I encountered some geared-up miners while
hunting as ash walker, and they started following me back to my base- by
the time I realized, it was too late because there were already visible
blood trails leading back to my nest (great emergent gameplay bit). It was
a terrifying eye-opener, and we were ultimately unable to defend the nest
from their ruthless attack (though it was close!).

Tendril conversion could be interesting! But there's a bunch of other
options for this scenario, dunno. Made me wonder how I could build up base
in way miners can't easily punch through.

**Comment by Hopekz** [comment]
It doesn't have to be a voting process, maybe make it so that you have to do a certain action to be a chef off the beaten path. If there are no other chieftains, make that action make the user a chieftain.

**Comment by Slinky5890** [comment]
I wouldn't mind getting a rule added stating that if you decide to slawn as a chieftain you HAVE to be an active leader. Afterall, players choose the chieftain egg of their own accord.

**Comment by Dagdammit** [comment]
From a design perspective... what if you could do something at the tendril
to become chieftain, assuming the position's open? Make it a bit
complex/non-obvious so the more inexperienced ash walkers won't know it's
an option.

**Comment by AdamElTablawy** [comment]
stale, put this in feedback thread on forums
