### ISSUE TITLE
hub msg cutoff

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#14026]
### Severity

Low

### Short Description

![](https://i.imgur.com/4G1iPLR.png)

### Reproduction

look at hub

### Round ID

0

### BYOND Username

Ynot01

**Comment by bruhlookatthisdood** [comment]
![image](https://user-images.githubusercontent.com/89947174/167231455-3e8a857a-a50e-44f5-97ee-9a67d9291af2.png)
code for it is fine

**Comment by Altoids1** [comment]
This has been a problem since #4949 and beyond. The main issue is that BYOND caps the character count of our Hub message by the literal character count of the HTML, rather than the amount of text rendered. We can probably manage to display these taglines better if the links were made shorter or removed.

**Comment by Oblisk234** [comment]
![image](https://github.com/user-attachments/assets/3a4a947f-c8f4-40c0-aced-569b5ccdce9c)
No longer have the same hub message (also sad that 55 players became 5 players in 2 years).
