### ISSUE TITLE
Make genetics complicated again

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#1417]
Genetics rework ideas:

Make it work like actual genetics, so you have to go hunting for people, 

People have alleles for different things which are generated at random, for example let's say bongo the clown is a  Heterozygous recessive hulk, 

Hh 

You'd be able to extract his genes and mix them with other things, such as if you found a Heterozygous recessive (more than one type of allele) monkey who was also

Hh

You'd be able to mix the two together to make hh, a hulk positive for example. 

What you wouldn't be able to do is just irradiate the genes, you'd have to go hunting david attenborough style for the genes you want. You'd have to work out if someone was recessive or dominant or a carrier of the gene at all via a handheld scanner, you'd basically go around dooting people with it to test their genes to see if they were what you wanted or not.

These genes would dominate everything, hair colour, eye colour, skin colour, who they look like (change their name) etc. so you could  change anything about anyone

You would be able to irradiate people to trigger a random mutation of one trait which could either be good or bad

All the powers would be rare genes and to get them you'd either need a good set of monkies or a lot of test subjects.

Why?

because utah brings a good point, genetics is kinda spammy and luck, i'd like to add some skill element to it, but i don't think the answer is to make powers unreachable

**Comment by Time-Green** [comment]
LETS MAKE GENETICS COMPLICATED AGAIN
VOTE KMC FOR TRUMP 2017

**Comment by Dzlan** [comment]
Fuck I support this a lot. It would make powers an actual rare thing. To the point where I might ACTUALLY WANT to see them around.

Making genetics hunt for people and a person having a small chance to have a super good gene, WOULD BE PERFECT!

**Comment by Super3222** [comment]
I had an idea for a genetics rework, but it'd be a lot different than this.

GENETICS REWORK:

First let's balance out some of the powers first.

The authenticity of super powers is present because of how it enhances the basics functions of every crewmember. It's down to earth, no action buttons attached, and easy to grip. This is what makes every super power great.

Hulk - They do 10 armor-ignoring brute damage per punch (lowered down from 18). Everytime they punch someone they get swung back as long as a dense turf is not behind them. In that case it makes them *flip. Prevents people from wallspamming.

TK - They cannot use TK on an item that's already inside of somebody's grip. Similarly, they cannot control anything inside of someone. Possibly nerf them forward to go as getting harmed (possibly could only be to the head) makes you lose your grip on an item.

Telepathy - They can instantly send a message to someone in a closeby radius. The message is in strong purple writing. It is very clear if someone uses telepathy or not because their head will glow. This power will replace Cloak of Darkness.

Jolt - They create of sparks by SCREAMING. Yes, this power works by putting !! at the end of your message. There's 3 intensity levels. First one, sparks start flying. Second one, harmful sparks start flying. They do 1 burn damage whenever hit by something. Third one, a whole lot of sparks start flying. They do 3 burn damage and fly out quickly. While using this it will drain nutrients depending on the level. The only way to cancel the sparks is to get attacked by something or rest on the ground. Using this over a wire will charge it, but will simultaneously draw out lots of nutrients and damage your body on either a clone or burn level.

Magnet - When they touch ANYTHING a strong magnetic pull will will grab anything metallic and pull it towards them. Runs on a cooldown, and when the cooldowns over they get a message like "you feel like the tips of your fingers are pulling towards something".

*** Possibly replace Xray with "Oracle": a super power that lets you see a glimpse of something behind a wall for a short amount of time?? Probably bad.

**** If chameleon doesn't already expose people when they get hit by something, than it should after this rework.

Second, let's take a look at genetics.

Currently there's a problem with genetics
* It's too fast to get super powers.
* It's not hard to get super powers.

My suggestion is this - 
Throw out being able to swap someones genetics at any given time.

And implant DNA capsules (looks like a bottle with swirling DNA) which can be used to shuffle around someones DNA.

A geneticist inserts a DNA capsule into the computer, clicks on a genome, and than has an X amount of tries until the DNA capsule has been drained. It's all dependent on what's left of the DNA capsule.

This requires any geneticist to run on a constant amount of DNA capsules.

Creating SE injectors, copying someones genetics, and all of that all operates the same. It however requires - guess what - DNA capsules to do.

When a DNA capsule is put inside of a computer it cannot be removed until the capsule is extinguished.
Once extinguished, the computer will go on a cooldown for a single minute allowing the geneticist to run around and do whatever. Maybe get off their ass and handle dead bodies.

DNA capsules could be ordered from cargo or made in R&D.
Normal version (genetics spawns with at least 3-6 / T1-T2) has 10 tries.
Super version (T3) has 12 tries. Probably costs some gold and/or silver.
Bluespace Version (T4) has 15 tries. Probably costs diamond/lots-o-plasma/gold.

**Comment by Dzlan** [comment]
Super, while I love all these ideas too.
I honestly, think it makes more sense for Geneticists to require crew members DNA.
Even if it was a mixture of this and that. I personally think grabbing crew members DNA should be a core concept.

**Comment by Kmc2000** [comment]
i just want mad scientist genetics running around kidnapping people for their genes ya know.


having minkeys that are instantly availible is somewhat GG

**Comment by AdamElTablawy** [comment]
This is a crap idea and it's not happening.

# Ignore everything you see in this issue req it's never happening.

It just ignores the primary issues of genetics.

We're doing goon genetics :^)

**Comment by Dzlan** [comment]
I mean, I don't really mind anymore,
Personally, Im enjoying Bay's codebase a lot more these days anyway.

**Comment by Time-Green** [comment]
Dzlan, stop with the negative attitude jeez

**Comment by Kmc2000** [comment]
Adam tells me goon genetics is lit

Port pl0x
