### ISSUE TITLE
Xenomorph Ruin Feedback

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#1478]
For people who do not have or do not wish to make an account on the forum.

So from what I was told overrall feedback was overwhelmingly negative, I want to know what and why people were so upset about the ruin so that I can see if there's anyway it can be improved upon. I did see a few xenos openly expressing their enjoyment in hive chatter so I know it's not a complete flop.

So first of all before you give feedback I want to know.

What role were you when you experienced the ruin, Xeno or Scientist? (Or maybe both if you've experienced both)

Also to note, I am aware of the involuntary bursting, this is a problem with normal xenos and I'll talk to a coder about seeing about a fix so that it prompts players instead of forcing them into the larva. Every other midround antag does this except borer so I dont believe xenos should be an exception even outside the ruin.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I was a xeno, was pretty okay in the beginning, we taunted the scientists into opening the shields a few times. Then finally someone managed to spit acid on a shield generator, everyone rushed in and killed the scientists. After that there was just nothing to do, we planted weeds everwhere, then one by one most people ghosted (and probably were pulled into a larva a few times).

**Comment by Super3222** [comment]
Alien code is currently designed where it instantly grabs a ghost with BE_ALIEN, without asking them first, and shoves them into a larva.

This creates an uproar with people that want to be cloned / don't want to be an alien atm / etc.

**Comment by Ratvar** [comment]
Aliens can acid lava into !!!space!!! tiles,creating pathways for them to run around laps and kill all miners,same with rocky walls.They then can acid space tiles into underneath layers of space-time continuum.Fix it,or they will run and depressure whole lavaland.

**Comment by Slinky5890** [comment]
I think the problem is there quickly becomes nothing to do for both sides. The xenos will eventually overrun the base and kill everyone, then have nothing to do. And if xenos aren't trying to escape, the scientists have basically nothing to do. 

I don't think letting xenos escape into lavaland is the solution, because then we're getting the whole station dying from xenos every third round.

**Comment by Hopekz** [comment]
I've played a few rounds as both. It's initially fun when the aliens start taking over etc. When the aliens finally wear down the scientists, there is nothing to do. I propose that we need a CLONING station for the scientists. The scientists should be able to slowly re-spawn (much like the aliens, except at a slower rate obviously) to keep up the containment. Add the ability to become the human test subjects in the lab. I want a role where the scientists barley arm a poor human being, then send him off to the cage to attempt to control them/ see what the aliens do. There needs to be more "experimental" things to do.

**Comment by Hopekz** [comment]
Sorry for the double post, but remove the ability for the Xeno's to open the doors. They should pry the doors, giving the humans THAT much more time to react to the xeno's sudden speed (and table hopping abilities)

**Comment by Dagdammit** [comment]
I've really fallen in love with the facility. It's such an interesting experience to actually be the scientist, knowing that all it'll take is one little screwup (or be the xeno waiting for one little screwup). 

Funny how well it fits the yogs title screen, too.

**Comment by Dagdammit** [comment]
Oh, one thought on there being nothing to do if xenos overrun the facility:

What if there was a secondary set of sleepers, sealed away from the rest of the facility, that only became available once all the initial xeno syndies had spawned & all but one had died? A "containment team" with their own armory (complete with grenades & flamethrowers) and directions to purge the facility. So when the aliens take over the facility, rather than trying to break out their next priority is building up the hive in preparation for the second wave of syndies.

**Comment by AdamElTablawy** [comment]
implemented and stale
