### ISSUE TITLE
Can't pull shit in space

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#14784]
### Severity

Inconvenience

### Short Description

Trying to pull shit in space is not fucking working (probably that bugfix PR)

### Reproduction

1. Preferably secure EVA gear
2. Go into space
3. Drag shit
4. Shit not being dragged???
5. Major mental breakdown
6. Major code breakdown
7. Major re-addition of a bug (or addition of a fix)

### Round ID

41812

### Test Merges

#14466 #14600 #14582

### BYOND Username

Addust

### Additional information

Inability to pull shit is pretty bad not gonna lie

**Comment by GraveHat** [comment]
Again I think this has similar problems to #14786 and #14882 the problem being the object your pulling and you not being synced with the direction gravity throws you in because I know you are still technically dragging the item and affecting it before it goes out of range. In #14882, you see the problem instantly as you stand still while the object your dragging follows the direction you were going in, while in #14786, this problem could only be seen if you move in the opposite direction of where your floating. This should also happen for living carbons your dragging through zero gravity as well.
