### ISSUE TITLE
Pulling objects in no gravity with magboots bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#14882]
### Severity

Inconvenience

### Short Description

Pulling weapon recharger with active magboots in no gravity lets them fly away from you while you're pulling

### Reproduction

- no grav
- active magboots
- pull recharger
- it flies away

### Round ID

41896 approx. at 31:00 as Dylan Rathens

### BYOND Username

Aquir

**Comment by GraveHat** [comment]
Might be caused by the same issue that's been reported by bop already in #14786 the way it seems to work is that you drop the object your pulling in zero grav, while yes it is still technically pulled and you can move it around with you as you move, the catch is that the object your pulling isn't totally synced with you and is still affected like how normal items are affected by gravity. In the other case, you were both heading in the same direction so that wasn't an issue until you head in the opposite direction, in this case, you're instead standing still and unaffected by zero grav using the magboots while the recharger is still affected by your motions and no gravity. This should be a problem for all the things you can grab that can pass through.

**Comment by warface1234455** [comment]
It happens on every objects structures
