### ISSUE TITLE
Syndicate Virology Ruins Banbait

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1493]
why does a ruin like this have a self destruct option? it is loaded with maxcap syndicate bombs spaced out in the ruin to blow it up.  this is purely ban bait for some retard or griefers to abuse. 

The ruin doesn't need these bombs in the first place. replace the stupid op syndicate weapons, that they don't need, with combat shotguns/revolvers/anything fucking else. this removes the need for the self destruction.  Other than that theirs nothing in this ruin that isn't on the station. 

side note: why the fuck does this ruin have self destruct option yet the giant deadly xeno ruin doesn't?

**Comment by Super3222** [comment]
The Syndicate Viro Ruin was a port from /tg/ which came with the self destruct feature by it'self.
The Xeno Ruin was built here on Yogs and never implemented with a self destruct feature.

**Comment by Stealthkibbler** [comment]
The Chemical Recon Outpost was designed by Kor Phearon around the idea of being a controlled environment for players to test death chems, deadly virus strains and other chemical concoctions, as-well as minor weapons testing outside of the station environment without rules limiting the players creativity.

TG doesnt have a bombcap on lavaland so the self destruct device is just 4 bombs in secure areas, however since we dont have a lot of the stuff tg has I had to pretty much downgrade the ruin by replacing and outright removing some stuff that was causing compiling errors.

The weapons are there to defend the facility against intruders, TG originally had toy guns instead of bulldogs and an m90, but all the snipers are accounted for. Only difference is on tg the agents spawn with the snipers in their hands.

This ruin isn't meant to be distinguishable or unique from anything the station has to offer, it is purely a tutorial ruin, the most interaction it gets with the outside world is the comms agent shitting over common radio.

The Xeno Facility on the other hand does not have a self destruct device because the last thing I want is scientists using bombs because they cant be arsed with fighting the xenos head on.

**Comment by puremanbird** [comment]
so once again Why are the bombs there in the first place.

**Comment by Super3222** [comment]
> Why are the bombs there in the first place?

So that nothing that they create can be identified / recreated by the enemy. "Evil" organizations do this all the time. It's just the theme of the Syndicate, and the /tg/ dev that worked on it did it.

**Comment by AdamElTablawy** [comment]
nope
