### ISSUE TITLE
Better money (from #1512)

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#1516]
Cash, dosh, moolah.

Raf brings up a good point, https://github.com/yogstation13/yogstation/issues/1512 but i don't think this is the way to go about it.

You get a credit card and spawn with a wallet by default, your credit card has your rank on it and is used at ATMS, in your notes/memory, you get your PIN which you use when you wish to buy stuff, you can also deposit hard cash at atms for even more money in your bank account, but note that if you try crack open the ATM and redeposit the cash it will detect that you are trying to scam nanotrasen and scream for sec to arrest you.

When at an ATM, you choose an amount from your bank to credit to the card so the card becomes worth that much

You get paid a base sum of 100 every 30 minutes of a shift, with a multiplier of X for the following jobs:

Tourist = 0.3 (you shouldn't be paid to be a tourist, but you can have some spending money from your parents)
Assistant = 1.1
Clown + mime = 1.3
Cook + Janitor + chaplain = 1.4
Botany = 1.5
Cargo tech = 1.6
Engineering = 1.7
Atmos = 1.7
Psychiatrist = 1.8
Security officers = 2
Medical staff (GEN. MD. VIRO.) = 2.2
Miner = 2.3 (their job is VERY hazardous)
Warden = 2.5

head payrolls:
QM = 2
CE + CMO = 2.7
HOS = 3.5
HOP = 4
CAPT. = 5

So for a captain, it'd be 100x5, 500 Credits payout which would be credited to their bank account

What you'd use it for:

You can handle your money via an ATM, which would be able to be broken open or emagged to shoot money out, you would be able to buy rare items from the clerk's shop, he would have a smartfridge where he can input costs of items and sell them. Every 15 minutes, a shuttle arrives from centcom (the ferry) with a loot box for the clerk, with snowflake clothing, materials and fun stuff inside which he can sell off as he pleases, it'd give him 4 items that are randomly picked.

Ideas on this front:

Toy car which you can drive around in
Toy space suits which look like iconic ones (think syndieshits and wizards)
Nerf guns
Light tiles
a modded bs capsule that spawns in a bouncy castle

There would also be a vendor in the clerk's shop which cannot be tampered with, this allows you to order things from centcomm with your OWN money to be shipped to cargo, once it arrives the crate would be id locked to you and have your name on the req. form taped to it, course a traitor QM could go to heaven with this and steal all the mail! (if it was for a smaller item, a lockbox which the clown postman can deliver)

The clown office will also spawn with mailman gear and a large duffelbag for smaller parcels, yes give the clown all your parcels, this is the best idea.

Additionally, for 2tc as traitor, you can snatch yourself an ATM skimmer module, attach it to an ATM and whenever someone uses their card on it, it gives you the name of the account holder, their card PIN and the amount deposited, to get this information you'd apply a special tool that the bundle comes with (Extra thin crowbar), which lets you prize off the unit to use the item.

Skimmers are undetectable, but will drop on the first stage of deconnning an ATM, so yes you could powergame like HELL and decon every atm you want to use to check for skimmers but they need a counter.

If crew objectives are ever added, it'd be great to see this tie in, like if you get 3/3 you get 1000 credits to use in the next round REGARDLESS of deaths (space logic, give money to your descendants)

To clarify, you do NOT keep money earned from each shift, it resets at roundstart and payroll is purely based off position AND when you die your money is NOT affected, unless it was on your card and someone gets your pin and credits your money to their account.

I can do the sprites for it if a coder wants to pick this up. (and if i've missed a job in the payroll please say so)

**Comment by Alek2ander** [comment]
A lot of servers have economy systems, but they only work on heavy-RP servers (unless being a meme is working).

**Comment by matskuman5** [comment]
What would be the point of having money apart from the fun toys from centcom?

Credit cards... eh.... I'd prefer if you could just stick your ID in the ATM

Crew objectives, YES Ive been wanting that ever since Goon implemented them.

**Comment by Super3222** [comment]
If you make an economy simple and coherent, than it could work. You have to figure out "what do people want to get" in a low RP server. You have to find an outstretched way in where it impacts everyone, everyone is affected by it, and everyone will gain something out of it. Otherwise it's useless.

I like KMC's model, it was something that I had in mind. Crew gets payed gradually, everyone gets a card, but a factor that I had more factors in my own system.

**Comment by Kmc2000** [comment]
What people want:


Weapons and powergaming shit

What they get:

Meme toys and bragging rights


Additionally, we could add general supplies like toolboxes and yellowgloves at a high cost

**Comment by Alek2ander** [comment]
It will always be easier to break into places and loot stuff. So that's what people will do. And that's half the fun of this game.

**Comment by Kmc2000** [comment]
Meh, i think people will use it for bragging rights and some sweet looking exclusive clothes. But we'd need to ask players what they'd want to buy if this were added

**Comment by Super3222** [comment]
Nobody cares about exclusive clothing. Well, maybe a few people
What people care about is
- Tools
- Medicine
- Belts
- Backpacks
- Basic necessities of their job
- Things that will help improve their job
- FOOD.
- General goods that the game can provide.

The point is to make windows like the chef, bartender, maybe even botanist, scientist, and cargo technician have to exchange money for the goods that they provide to the consumer (crewmember).

Just keep in mind that you don't want to completely turn someone into a hobo unless they never do their job. There is a certain way to control this, me and StealthKibbler talked about it in the past. Apparently LIFEWEB did this before too.

> It will always be easier to break into places and loot stuff. So that's what people will do. And that's half the fun of this game.

That's also why we have security officers and ID protected vendors. Break-ins are bound to happen, but the backlash will come out immensely.

**Comment by Kmc2000** [comment]
It's not job based unless we tie in crew objectives, you get your basic payout depending on rank.


So yeah greytide pays, go figure

**Comment by Super3222** [comment]
Assistants wouldn't be paid. In fact, they could spawn in giant dirty, black overcoats with a bottle of rum in one of their hands for all I care (d20 did something like this). Neither would tourists get paid for that matter. They'd spawn with a lefty amount of space cash to hand to other people in order to get tours into departments and all that.

Tying crew objectives would increase the motivation to actually sell things or even earn money, but the system can't be balanced solely on that. Making it job based places it at the core of SS13 which is a bunch of different jobs "working together" at the familiar cause of keeping the station intact and together. The economy would have to work towards rewarding participants of the cause, and letting them live a more broader life than shitheads that don't work at anything.

Your idea of an economy where people get money even if they're lazy or the most hardworking, and then get loot wouldn't work because nobody's going to care. If it doesn't matter whether I'm running around naked with a sign that says GREYTIDE WORLDWIDE compared to my co-worker who's maxing out research than the economy is nothing more than a joke. It's also a factor in why communism has always failed. If we're making an economy we have to do it by making it IMPACT the crew. Which is why it HAS to be job-based, it has to be FUN to participate in, and it has to give something enjoyable in the end.

**Comment by matskuman5** [comment]
Also doctors earning more than sec? U wot m8

**Comment by enailz** [comment]
> What people want:

Weapons and powergaming shit

What they get:

Meme toys and bragging rights


Maybe that's why they want weapons and powergaming shit

**Comment by Frostben** [comment]
Super brings huge insight into this and i love it, money based job objectives could possibly help with this? Give people some simple job related objectives to earn some simple money on and then a important objective which they can gain lots of money for. For example the doctor has a simple objective of restoring 5 crew members to full health that will get him 100 dollars into his account then a large objective of keeping at least 50% of the crew alive at round end that will give him 1000 dollars.

**Comment by Kmc2000** [comment]
@stealthkibbler


Hence the
>if crew objectives are ever added part

**Comment by AdamElTablawy** [comment]
poor idea.

i'll speak to KMC about changing this.
