### ISSUE TITLE
Agents in the lavaland recon base can't change syndie ID cards

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#1518]
You can change it's appearance in the chameleon menu, but you can't forge a new name, making the voice changer you get useless. 

I'm guessing they don't spawn with the traitor/syndie faction, so they can't mess with the card

**Comment by Super3222** [comment]
I thought non-traitors could always forge agent ID's?

**Comment by Time-Green** [comment]
Nope, only traitors and puke ops can change them

**Comment by Stealthkibbler** [comment]
well guess what you wont even be able to use the chameleon menu anymore because of another pr reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Ratvar** [comment]
Make subtype usable by nontraitors,will make one good loot for miners?

**Comment by Dagdammit** [comment]
Only the comms agent needs a changeable ID, to take advantage of the the voice changer.
