### ISSUE TITLE
New abductor glands

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#1530]
We need more abductor glands, and I am calling upon the people to think of them.

They cannot kill the owner however.

**Comment by utahclock** [comment]
One that makes you change random colors.

**Comment by Time-Green** [comment]
That's actually a good idea

**Comment by Rocks4Free** [comment]
one that gibs you

**Comment by Time-Green** [comment]
FUUUUUUUUUCK YOUUUUUUUUUUUUUUUUUU

**Comment by Frostben** [comment]
one that slowly turns you into a random xeno lifeform

**Comment by utahclock** [comment]
One that turns you into fly, skeletion or shadowperson

On Dec 31, 2016 6:51 PM, "Frostben" <notifications@github.com> wrote:

one that slowly turns you into a random xeno lifeform

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/yogstation13/yogstation/issues/1530#issuecomment-269887820>,
or mute the thread

**Comment by utahclock** [comment]
One that enhances your hearing you can hear through walls

**Comment by ShadowDeath6** [comment]
One that gibs you

**Comment by Super3222** [comment]
one that gives you, but also leaves a giant cloud of plasma behind

**Comment by Super3222** [comment]
one that gibs you, but also leaves a cloud of plasma behind

**Comment by Time-Green** [comment]
Ok, I am making one that gibs

**Comment by Stealthkibbler** [comment]
One that injects you with random healing chemicals

**Comment by Ratvar** [comment]
The one that teleports you to your abductor shuttle,gives you standart ayy jumpsuit and radio,makes you into ayylien,gives you their radio,telepathy and thralls to ayyliens,making their team bigger.

**Comment by Dagdammit** [comment]
-Gland that makes it so hugging someone has a 50% chance to temporarily change your UI and UE (name and physical appearance) to that of the person hugged, same as the effects of a DNA injector.
-Gland that gives you a zombie's boosted limb loss chance and easy limb reattachment. (I like Stealth's version where damaged limbs fall off and regrow, but I also like this version because you can easily become a frankenstein bearing someone else's limbs)
-Gland that gives you night vision and makes bright light (normal fully lit conditions) deal small amounts of continuous eye damage unless you have flash protection.
-I don't know temperature mechanics, but: A gland that makes you like a walking inverse space heater, constantly cooling the air around you. Better grab a warm coat. (Bonus points if the cold is instead your new comfortable temperature and exposure to room-temperature air brings up the lowest grade of heat warnings.)
-I'd love something that makes it so your head can fall off (say, when your head's taken 50 or more brute damage?), but this doesn't kill you- you're either a talking head or a walking headless corpse, either works for me.
-A gland that makes it so when another abductee says something, you sometimes echo them (your character involuntarily says the same thing at the same time, even if the other abductee was on the opposite side of the station)
