### ISSUE TITLE
Make carded AIs start with subspace radio enabled (and maybe wireless functions)

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#1588]
Title says it all really. This is only really because I wanna make it easier for AIs to fuck over traitors, and for AIs not having to bug whichever nonantag carded them for whatever reason to enable their shit.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Radio is okay but wireless function will fuck up people trying to stop rogue AIs (which is why they are carded usually)

**Comment by Slinky5890** [comment]
Yeah  I haven't got my heart set on wireless function.

**Comment by Dagdammit** [comment]
If radio and wireless are both on by default but you can turn them off BEFORE carding someone, that seems fair.

**Comment by Slinky5890** [comment]
Being able to activate/deactivate via the card before having an actual AI in would be good, yeah.

**Comment by AdamElTablawy** [comment]
AIs are not here to 'fuck over traitors' and this is intentional behavior for carded AIs. They should not start with wireless, etc, as this makes the hardest objective even harder and makes it hard to card and kill a rogue AI before it switches turrets back on again/flashes you/bolts door, or something
