### ISSUE TITLE
Pressure Valves do not work.

### ISSUE THREAD

**Issue by BurgerLUA** [yogstation13/Yogstation#16490]
### Severity

Inconvenience

### Short Description

Pressure valves do not transfer gas at all, regardless of the setting.

### Reproduction

1. Put in a pressure valve.
2. Discover that it does not transfer gas regardless of the setting.
3. Delaminate the supermatter.
4. ????
5. Profit.

### Round ID

43825

### BYOND Username

BurgerBB

**Comment by warface1234455** [comment]
Not trasnfer due to gas was too hot and pipe got clogged, not bug

**Comment by warface1234455** [comment]
use straight pipe for sm setup next time

**Comment by BurgerLUA** [comment]
> Not trasnfer due to gas was too hot and pipe got clogged, not bug

I tested it with room temperature co2 and it did not work.

**Comment by warface1234455** [comment]
> > Not trasnfer due to gas was too hot and pipe got clogged, not bug
> 
> I tested it with room temperature co2 and it did not work.

its either pressure clogged

**Comment by warface1234455** [comment]
Cannot reproduce, also i havent encountered this bug through my atmos days before

**Comment by Firewolf34** [comment]
I dunno, did you try to reproduce it? I think these things aren't working as intended. Or if they are, they need to have some explanation or something to make them more intuitive to use... Because they aren't even moving gas out of a standard oxy tank. This is in the first 5 mins of a locally hosted server straight off master branch.
![image](https://user-images.githubusercontent.com/2159739/204418560-18c87ce4-f4c8-495f-b2df-6629fe5166b5.png)
![image](https://user-images.githubusercontent.com/2159739/204418885-69ed7d0a-0a88-4833-a8e4-d6cff58dde73.png)
It's also filled with freakin' typos. What the hell could I be doing wrong here

**Comment by warface1234455** [comment]
> 

That's a temp pump, it transfers heat not gas

**Comment by warface1234455** [comment]
Unwrench the valve and wrench

**Comment by warface1234455** [comment]
Should work again

**Comment by Firewolf34** [comment]
![gastank-reproduce](https://user-images.githubusercontent.com/2159739/204423825-51d36486-77f5-4fe0-9341-3234d78cdd54.gif)
Pressure in tank was well above set pressure.

**Comment by warface1234455** [comment]
Odd

**Comment by Firewolf34** [comment]
Lol. Spent 30 minutes bashing my head against the code trying to figure out the problem with varedit and doing the pressure math manually. The problem is, of course, stupid simple :laughing: 

What's wrong with this picture

![image](https://user-images.githubusercontent.com/2159739/204428845-aebaf3c0-e34d-475b-b6d6-563486217516.png)

For the future - at least test the thing before you write "cannot reproduce". This was a valid ticket and would have been closed needlessly...

**Comment by BurgerLUA** [comment]
society

**Comment by warface1234455** [comment]
> Lol. Spent 30 minutes bashing my head against the code trying to figure out the problem with varedit and doing the pressure math manually. The problem is, of course, stupid simple 😆
> 
> What's wrong with this picture
> 
> ![image](https://user-images.githubusercontent.com/2159739/204428845-aebaf3c0-e34d-475b-b6d6-563486217516.png)
> 
> For the future - at least test the thing before you write "cannot reproduce". This was a valid ticket and would have been closed needlessly...

Lmao, i have been using this shit for hundreds of rounds

**Comment by warface1234455** [comment]
Even use one to do toxin, works everytime

**Comment by warface1234455** [comment]
> I dunno, did you try to reproduce it? I think these things aren't working as intended. Or if they are, they need to have some explanation or something to make them more intuitive to use... Because they aren't even moving gas out of a standard oxy tank. This is in the first 5 mins of a locally hosted server straight off master branch. ![image](https://user-images.githubusercontent.com/2159739/204418560-18c87ce4-f4c8-495f-b2df-6629fe5166b5.png) ![image](https://user-images.githubusercontent.com/2159739/204418885-69ed7d0a-0a88-4833-a8e4-d6cff58dde73.png) It's also filled with freakin' typos. What the hell could I be doing wrong here

btw, did the round started while you were doing it

**Comment by warface1234455** [comment]
atmos won't be active if round hasn't started

**Comment by warface1234455** [comment]
is_operational() proc shouldn't be true there but still it's IF OR so if on was true it would still active anyway

**Comment by warface1234455** [comment]
![image](https://user-images.githubusercontent.com/89688125/204486268-b45b0460-d6ca-4907-8203-98c6e1985d28.png)
look closely

**Comment by ShoziOffical** [comment]
ok my apologize, somehow my eyes see it as "gas pump"

**Comment by Firewolf34** [comment]
lol no worries. It does kinda look like a shrunk down gas pump. and UI is identical.
