### ISSUE TITLE
Seismic arm can be used in time stop

### ISSUE THREAD

**Issue by Majkl-J** [yogstation13/Yogstation#17021]
### Severity

Exploit

### Short Description

Seismic arm can be used in time stop scenarios, holopara and sepia edition.

### Reproduction

1. Do funny time stop
2. Timestop person with seismic arm
3. They can jump out of it???? Or just target YOU instead.

### Round ID

Round #44269

**Comment by Notamaniac** [comment]
I can't seem to replicate this. Abilities seem to get disabled when timestopped. You can perform a lariat INTO a timestop though and hit people inside though, but I don't know a good way to handle the forced movement since it seems to be ignoring the walk(L, 0) call when the mob gets frozen. Likely because of forcemove(), and stun code not forcefully stopping the interaction... but that's just a guess.
