### ISSUE TITLE
Bag of holding is invisible when worn

### ISSUE THREAD

**Issue by warface1234455** [yogstation13/Yogstation#17081]
### Severity

Inconvenience

### Short Description

Title

### Reproduction

1. Wear boh
2. Its invisible

### Round ID

N/A

### Test Merges

#16989 #17049

### BYOND Username

Warface1234455

### Additional information

All subtypes of bag of holding show invisible when worn aswell

**Comment by Notamaniac** [comment]
Alright a little closer to the solution of this problem
in Yogstation\yogstation\code\game\objects\items\storage\backpack.dm there's this proc
buildwornicon() which is causing runtimes. Probably because for some reason it changes inputs of the proc, and buildwornicon() is getting called elsewhere, probably with different arguments. So we have to fix this proc for the bags to show up in hand again,

**Comment by ShoziOffical** [comment]
yeah i knew that proc did something
