### ISSUE TITLE
Revert the cost change on Eswords

### ISSUE THREAD

**Issue by YogsMcree** [yogstation13/yogstation#2021]
Dual esword is now essentially the only thing you can buy. Costing 14 points you are left with 6, which essentially means buy some soap and noslips and go loud. This change promotes loud murder traitors, stops yku from buying an emag, and makes the sword more than 50% less useful. Not a good change

**Comment by AdamElTablawy** [comment]
Buying esword = You're going loud anyway

**Comment by YogsMcree** [comment]
Not true at all. Buying esword means if you get caught you want to have a backup plan that will get you out of taser fire. That or add energy shield into pda uplink to promote defensive play style 🤔

**Comment by ShadowDeath6** [comment]
>buying esword means you get out of taser fire

What?
Also it's intended to disallow emag from being bought, because emag has had immense powercreep over time.

**Comment by YogsMcree** [comment]
Incredibly noticeable, incredibly obvious, incredibly dangerous to use powercreep? Between AI, prints, onlookers and unfortunate timing, a crypto alone is hardly the most powerful item, and getting a camera bug to make it viable racks it up to 9tc to be safe to use without getting caught, perma'd or killed.

**Comment by ShadowDeath6** [comment]
all access, not obvious at all unless you spam examine people since there are no messages and no sounds that are signature to it, can hack literally everything, can flash + hack a borg to make the AI guaranteed dead and also immensely lethal, not to mention the powercreep of almost every feature added having a special emag effect as well as emagged cargo being a thing

**Comment by Jc1469** [comment]
:balance_scale: :police_car: 

Either revert the price change or the block change.  
Or I'll just revert the PR and we can go on the magical revert revert revert loop journey.

You don't balance an item by destroying the viability and then making it more expensive so nobody will buy it at all.  That's how you make it redundant.  

:balance_scale: :police_car:

**Comment by Cruix** [comment]
There are plenty of traitor items purchased less frequently than double eswords and I have no doubt that this will continue to be the case.

**Comment by ShadowDeath6** [comment]
>destroying the viability

It's still a 3shot along with full energy projectile immunity (with reflect, too!) as well as unarmed immunity and a 25% chance to block anything that's supposed to counter it such as thrown items or bullets or stunbatons as well as being a guaranteed knockdown stun or dismember due to how shitty item attack code is. ALSO DON'T FORGET ABOUT ARMOR PENETRATION SO EVEN IF YOU DON'T GET STUNNED BY THEIR TASER / RNG KNOCKDOWN YOU CAN STILL GET DISMEMBERED AND TAKE AT LEAST 75% FULL DAMAGE

Also being able to emag into the armory as soon as nobody's looking for tasers and shit that make your high chance of kill even higher just creates some shit autism combo that's almost as bad as the old combo cafe was. 

Don't talk about shit being unviable when it's one of the most annoying weapons to play against since there are no real direct counters to it as the traitor arsenal as well as the sword itself have gotten large buffs in terms of defensive and offensive items that just make it unfun to fight

See; emag + dual esword for all access anywhere since you can't get locked down and the emag shits on all unbolted doors
See; dual esword + noslips + lube (this got nerfed a while ago but it's an example)
See; ebow + esword

Dual esword is a crutch item that works way too well in literally every combat scenario and lowering its viability in all situations is a decent change for now
Also the esword price is still lower than it was before the buff, where it was 8 tc, and you could do very little with other items when using the dual esword as you sacrifice other traitor options for the sheer offensive potential of it
