### ISSUE TITLE
could jobs be assigned before antag roles?

### ISSUE THREAD

**Issue by Mrcreepssss** [yogstation13/yogstation#2050]
what i'm asking for is a small change in the assigner becouse sometimes when i wanna play AI i don't get it becouse i was assigned tatorduty, and i get made like an assistant. it's really annoying. i don't imagine this would change too much though.

**Comment by AdamElTablawy** [comment]
This already happens.

**Comment by ShadowDeath6** [comment]
antag is assigned before job
If you don't want to play antag then turn off antag roles

**Comment by ShadowDeath6** [comment]
Also this probably won't be changed due to the fact people who play silicon or security lose out on their chances to play antag and it causes less sec than normal

**Comment by MacHac** [comment]
That's not entirely true.

To my knowledge, traitor AIs are still spawned after the AI player is picked.

I believe I did this partially because it ensures that traitor AIs have some experience as AI, or at the very least meet the requirements to spawn as one.  It also allows them to spawn independent of the gamemode, which is why we don't have another 12 modes labeled like
- Malfgang
- Malfling
- Malfwiz
- etc.

This is the only antag done this way, and I ultimately did it because in oldmalf fully half of traitor AIs (at a minimum) had never played as AI before, resulting in a lot of strife and sadness, as well as a close-to-zero chance that players who actually did play AI frequently would get the role.

Shadow is correct in noting that most antagonist roles aren't done this way, because otherwise roles that can't spawn as antagonist would be deserted as nobody wanted to give up their shot at playing the bad guy.

**Comment by Mrcreepssss** [comment]
either way, i do think that malf happens too rarely. i've been pulled from AI to be another antag a dozen times, never the opposite, honestly i don't get how this does work.
