### ISSUE TITLE
Go use the suggestions subforum for making suggestions instead of the github. It's cluttering things up too much.

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#2071]
Title

**Comment by Slinky5890** [comment]
The one with 'Old-' next to it? Might wanna get council to update the subforum for people to want to use it.

**Comment by 00aquir** [comment]
Isn't this what Labels are for? You can see only the bugs, etc.

**Comment by matskuman5** [comment]
It's way easier cause suggestions are here

As 00aquir said, just filter them

or we could create a system where a suggestion gets closed after a week or something

**Comment by 00aquir** [comment]
closed in a week? while bugs are obvious, suggestions need more people and concensus, ergo more time...

**Comment by 00aquir** [comment]
especially when people don't address them because they are down the list

**Comment by EthanMalakay** [comment]
i will use the fórum now 👍

**Comment by ShadowDeath6** [comment]
>be on suggestions
"Go to github"
k
See this issue

**Comment by EthanMalakay** [comment]
oh ye ur right, what to do now?

**Comment by matskuman5** [comment]
Closed since git is for bugs, not suggestions

**Comment by Mrcreepssss** [comment]
"especially when people don't address some just because they are down the list and not visible (when they got closed temporarily from outside, but later re-opened. there are some issues like that.)"
this for putting in a seperate forums thread could help, i honestly was gonna ask about this myself.

"Closed since git is for bugs, not suggestions" matsku, i think you're joking but for safety i'm gonna say it anyway: look on the forums for suggestions (not old) it'll linke back to git.

**Comment by 00aquir** [comment]
"in a seperate forums thread"
It would be nearly the same with the forums when there are many suggestions, and you couldn't even search a keyword to see all issues about one thing... it would beclunkier

**Comment by Mrcreepssss** [comment]
yeah okay fair point.
