### ISSUE TITLE
 Almost all of Demo Replay is Black

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21003]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Loading Demo Replay via link yields a black screen, with all sprites being black except for paintings. Tried loading Demo Replay on multiple round ID's, across both Firefox and Chrome, with different connections, and with extensions disabled; with same result each time. Font is also noticeably different than screenshots from others using the application. Using console states TypeError: Failed to Fetch

 Submitted by: gigavoltz (309557612809289729)

**Comment by Humanbb** [comment]
Upon trying to replicate the problem using the same laptop I tried above, but at a different address, the Demo Replay worked without issue. It's likely that my issue has instead something with my home network blocking the fetch command for whatever reason and not specifically a browser or coding issue. I'll look into it on my end, but if you have any insights they would be appreciated

Thanks, 
(Gigavoltz)

Edit: verified that the issue was because of my Network filter (pi-hole), so I need to figure out what exceptions to add
