### ISSUE TITLE
Wet floors dry too fast 2: Electric boogaloo

### ISSUE THREAD

**Issue by Oakboscage** [yogstation13/yogstation#2109]
Wet floors still dry almost instantly after being mopped. Which makes being a janitor NO FUN ALLOWED and make the wet floor signs useless junk.

It's time to make janitor great again by setting the drying times to something more reasonable like they used to be. I believe this should be a rather simple fix and I'd do it myself if I had any idea where this shit is located and could trust myself to not just break everything forever.

**Comment by Jc1469** [comment]
https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/game/turfs/open.dm#L111 :ok_hand:

**Comment by Oakboscage** [comment]
I looked at that but I couldn't figure where wet_time is actually calculated based on amount of water.

**Comment by matskuman5** [comment]
Sure I'd support this, but I think that the last time this was discussed Cruix said that changing this would require reworking the entire new slip code, so idk

**Comment by Oakboscage** [comment]
Why do we even have a new slip code if everything is broken now?

**Comment by Cruix** [comment]
I never said that.

**Comment by Cruix** [comment]
The reason they dry so fast with a mop is because it scales with how much reagent was splashed on the floor, and mops only apply 1 unit of water.

**Comment by ShadowDeath6** [comment]
If you want to slip people just fill a cup with 50u water from a sink and throw it at the ground

**Comment by Oakboscage** [comment]
Sure you could fill a bucket or cup to slip people but then it's clear it's intentional. Takes a lot away from being antag janitor where you could slip + robust targets and the slip itself wasn't clearly intentional so you had the benefit of the doubt if someone sees it.

I also think that the dynamic between a janitor doing his job and the crew who always gotta go fast was an important part of 2D spacemen.

**Comment by Cruix** [comment]
It used to be when mopping was the only way to clean floors quickly at round start, but then the janitors had to go fast too and they got SPACE CLEANER SPRAYBOTTLES and SPACE CLEANER BACKPACK TANKS and SOAP and CLEANER GRENADES and they got them all at ROUND START because GOTTA GO FAST CANT WAIT FOR CHEMISTRY OR RESEARCH.

That dynamic is probably gone along with RnD needing acid from chemistry, chemistry needing corn oil from botany, botany needing exotic seed crates from cargo, cargo needing the bartender's shotgun to open crates, xeno needing anything from anyone, and anyone needing to communicate with anyone outside their department in general.

There is an advanced mop in RnD that generates its own water, but no one ever makes it because it is worse than the soap janitors get at round start.

**Comment by ShadowDeath6** [comment]
Make janitors have to clean the ground with their pda until r&d gives them a bucket

**Comment by Super3222** [comment]
Eh. Janitors should be able to slip people by doing their job and mopping. That's just one of those core SS13 things. Can't we make mops apply more units?

**Comment by Oakboscage** [comment]
Mops applying more units might make the cart/bucket run out too fast if it uses enough to make floors actually stay slippery for a while. However, while I am no coder, I think this could be worked around by making the mop automagically create more water when it's wet. So the while the mop still uses the same amount as before it would apply X times that.

**Comment by ShadowDeath6** [comment]
Just make the mop bucket hold more. How can 1u of water which is literally a fifth of a third of a syringe clean anything

**Comment by Dagdammit** [comment]
Having the mop apply more water than it actually uses sounds solid. 

Also woah, advanced mop makes its own water? Good to know, I assumed it just had boring double capacity or similar.

**Comment by Mrcreepssss** [comment]
all hail the advanced mop! creator of all the water in the universe! and the experimental welder which creates all the welding fuel! ALL HAIL THE GODS CONSTRUCTED BY RND!

**Comment by Oakboscage** [comment]
Coders pls

**Comment by Super3222** [comment]
I was going to fit it into my misc fixes and tweaks PR, by Cruix was making a pr doing something similar so I reverted the changes.

But no seriously. This N E E D S to happen, and Cruixs PR doesn't help. The slip gag is suppose to end funny in the sense that it happens on accident/doing your job. Not from being an intentional dick and mopping the same tile a hundred times.

This separates the need to put down a wet floor sign and the need it too.
