### ISSUE TITLE
Lavaland/ghost roles and preferences

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#2120]
Add prefs (with low-high scale)for existing all existed ruin ghost roles [(Cosmic) Ashwalker, Free Golem, Outpost Doctor/Officer, Syndicate Officer/Scientist, Prisoner, Lifebringer, Bard, Space Bartender], leaving spare spawn sleepers for ghosts later but giving those with the preference set priority. Would "punish" pre-round observers (yes, I'm one of them), discourage lavaland meta-exploring, eliminate the round start spam click ghost rush, encourage them to ready up instead, and still allow lavaland roles.

**Comment by ShadowDeath6** [comment]
What would this accomplish exactly, I'm confused. This makes it so you can select a ghost role to be at roundstart rather than observe and be the same ghost role at roundstart?

**Comment by Frostben** [comment]
I believe the idea is that people who are unable to get these ghost roles by observing are instead integrated into the crew so that there are more active players in the round

**Comment by Dagdammit** [comment]
Ohhh, that makes sense. Give all roundstart lavaland ghost spawns a coinflip chance of being considered for roundstart job assignment, for those who've given them a priority. Server probably wouldn't/shouldn't do any roundstart lavaland spawns for lowpop.

Maybe the coinflip should be for a ruin rather than individual spawns- that way Orion Medical Outpost and the like have better chances of getting multiple staff members.

That actually sounds interesting as a shaft miner too, since those ruins will always be more interesting (and no longer easy lootfests) when their occupants are awake and active by the time you get there.

**Comment by ShadowDeath6** [comment]
Forcing people into jobs they want will _always_ result in suicides, and I don't think ghost roles have such an impact on the station ( aside from ashwalkers who only exist to grief miners anyway) that they need their own occupation preference. There's a reason they were designed so that people can spawn repeatedly.

**Comment by Dagdammit** [comment]
I don't think anyone's saying we NEED to make players play lavaland
roundstart spawns "for the good of the server". I think the other guy's
right, and OP just meant making a limited allowance for those interested in
doing so. Right now, they just hit "observe" when the 3-minute countdown
starts and see if there's anything good. Not the most game-ruining state of
affairs, but there could definitely be a better way.

Alot of hypothetical pitfalls here can be prevented based on how the
roundstart spawn decides things. Say it hypotheically turned out medbays
were going unstaffed because everyone wanted to be Orion doctors instead:
we could just make it so the server always staffs the medbay first.

On Mon, Apr 10, 2017 at 6:14 PM ShadowDeath6 <notifications@github.com>
wrote:

Forcing people into jobs they want will *always* result in suicides, and I
don't think ghost roles have such an impact on the station ( aside from
ashwalkers who only exist to grief miners anyway) that they need their own
occupation preference. There's a reason they were designed so that people
can spawn repeatedly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/yogstation13/yogstation/issues/2120#issuecomment-293121678>,
or mute the thread

**Comment by Super3222** [comment]
Please contact the Council about opening a suggestion forum on our website.
https://forums.yogstation.net/index.php?threads/bring-back-the-suggestion-subforum.13093/
