### ISSUE TITLE
Make it possible to hang yourself

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#2179]
i want to see people hanging in front of the bridge.

Just make it by hitting a chair with couple of cables making a noose and you're able to place yourself and other people in it making it a creative way to kill someone though they are able to resist out of the noose in 20 seconds making them stunned for a few seconds., you can still revive the person though.

Adding the creaking noise of hanging would make it even better.

**Comment by Time-Green** [comment]
A key feature of all nanotrassen stations is the lack of roofs due to the budget so this isn't really possible

**Comment by fonedsky** [comment]
It's a thing on Hippie or /vg/ if I recall correctly. You use a cable coil to make a noose, then drag a chair and hang yourself. It deals slow oxyloss damage and doesn't give you the suicide variables because memes I guess.
It also has the creaking noise you want, and a bunch of spooky sad messages (the sprite even swings left and right).

**Comment by Lightning38088** [comment]
^ Thats where i remembered it from, and if i recall correctly the noose fades as it goes up. I like the swinging back and forth reee.

**Comment by Jc1469** [comment]
did you know if you have a phone and stand on a stool and suicide, you hang yourself
