### ISSUE TITLE
Many useless ghost teleport destinations

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#22270]
### Severity

Low

### Short Description

34 "Bluespace" destinations 

### Reproduction

1. Ghost
2. Open Jump to mob or Teleport menu
3. Search "bluespace"

### Round ID

Round #53075

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/18729830/38dde2ea-02ba-45fd-b2a4-c42247c6d586)

Two adjacent issues:
1. "Teleport" and "Jump to mob" menus are identical, no use for two buttons on the ghost bar.
2. Clicking names to ghost teleporting to certain, multiple same name mobs like "Gym Rat" teleports to the same, singular Gym Rat.
3. Search function doesn't fully filter options until closing and re-opening the drop down selection.

**Comment by Oblisk234** [comment]
Can't replicate, looked through jump menu on both localhost and server and there wasn't any areas which was duplicated or existed for no reason.

**Comment by Oblisk234** [comment]
From my observations, bluespace is used for pods and shuttle transit, that's why there is so many. Not an issue.

The Teleport and Jump to mob menus are identical yes, whether one should be removed is debatable.

Can't replicate same name mobs being identical, maybe consider that two mobs were on top of each other (Thus, not moving)?

Can't replicate search function not working properly, seems to be working without needing to close or reopen the dropdown.
