### ISSUE TITLE
Some gamemodes are still out of rotation.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#233]
Pls fix already.

**Comment by Super3222** [comment]
This is a database problem. @oisin100

**Comment by Super3222** [comment]
I'm thinking it would have to come down to a council vote for the weight of each mode or to be circulated inside of the coder group chat.

**Comment by MacHac** [comment]
This isn't a database problem, it's a config problem.  The chances are set in config/game_options.txt

Tragically, we missed our chance to copy TG's gameoptions wholesale during the rebase, and that does in fact mean that the ball is in the council's court now, so to speak.

Frankly, I don't see how a yes or no vote is going to set percentages, so anyone who wants this fixed should probably set up a formal proposal and present it to them so that they can vote on it eventually.
