### ISSUE TITLE
stealthy book boxes are not stealthy cause

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2342]
they emmit box sound when you pick them, put into backpack, interact in any way or form. 
If you see librarian give you Woody Got Wood to give to prisoner and it emmits box sound-it got fucking wirecut, alerm.
Why the fuck boxes even emmit sound when you pick it up

**Comment by drderp3635** [comment]
English please

**Comment by Frostben** [comment]
Apparently books that have been hollowed out using wire cutters make backpack sounds when you pick them up and interact with them. The author does not approve of this because books are not backpacks and trying to smuggle weapons/tools to help a prisoner using hollowed books is very risky because security will be able to tell that the book is hollow and will arrest you.

**Comment by Frostben** [comment]
EDIT: security will be able to tell that the book is hollow not because they interacted with the book as if to read it but because the book made backpack noises.

**Comment by Frostben** [comment]
@drderp3635  Is this translation legible for you?

**Comment by ShadowDeath6** [comment]
Easy fix
