### ISSUE TITLE
Issues with the Free Miner space ship

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#2354]
There's some things missing on the free miners space ship. For 1, there's no charging pad next to the mech bay power port, so you can't actually charge your mech when you build it
Another issue is that there is no surgical equipment inside the medical dufflebag(viewing this as a ghost) making it impossible to do limb surgery on. 
Unsure if there are anymore issues with it, but that's all i've seen as of so far.

**Comment by LarissaMayrink** [comment]
You can print the surgery tools after the basics has been set and a autolathe built from derelict materials. But yeah, the mechbay is fucked and you can't really charge it, ever, you need to buy a plasmagen from the vending machine or just give up.

**Comment by Cruix** [comment]
There does not need to be a charging pad next to the charger, the pad is just for looks. The charger does not sync with the right tile because of a bug with the maploader, but you can easily fix it by using a screwdriver and a wrench.

The medical dufflebag is not supposed to have any surgery supplies in it, and the free miners have no reason to do limb surgery anyway.

**Comment by someoneunkown** [comment]
Alright, I see. I wasn't told that.
