### ISSUE TITLE
Kinetic Accelerator rework

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#2398]
# Right now
Kinetic Accelerators are cool and all and then science gives you double wielding hyper KAs of destruction.

# Idea
I kinda want to do the same thing /tg/ with KA's. They have modkits wich you apply to the KA to improve them.

I want to split them into parts. No idea how many and what kind. You could buy new parts to replace the old parts with to improve your KA in a certain direction. Longer range, higher damage, lower cooldown etc.

Basicly I want to know cool idea's for upgrades, alt fires and attachments. I am not leaving the kinetic resonator out of it, and if you guys want I can add the kinetic crusher( A double wield KA you use to mark from a range and then melee for massive damage)

**Comment by Super3222** [comment]
When I was the midst of my lavaland overhaul I came up with multiple ways to rework kinetic accelerators.

Super kinetic accelerators are deleted and gone. Poof.
The only alternative KA is hyper which can be picked up from R&D.
Hyper has an overheat time of 15 instead of 14.
Hyper still does splash damage.
Hyper's damage deals 11 damage instead of 12 in a non-vacuum area. (i think it's multiplied by 4 in a vacuum?)
Hyper has a range of 3 instead of 5.

This is to give space for upgrades/mods, while still making it the "better" version of the KA.

Now when we're making attachments they have to cover our guns stats. I looked into the stats awhile back, and there's not a lot of unique features to the KA that we can pick at. Here are the stats that I was able to come up with though.

- Damage: how much brute damage does each blast do?
- Range: how far can you shoot the blast?
- Recharge: how long does it take for the next shot to recharge?
- Control: how powerful is the recoil on the accelerator?

With this in mind, we can create 3 different types of mods.

Overbarrel - These generally upgrade the damage and control of the weapon. They reduce range and recharge.
Bipod - These generally upgrade the range and the recharge of the weapon. They reduce damage and control.
Special - These generally don't change any of the stats, but they sure do help in other areas. A good example of this would be the hotspot.

Normal Kinetic Accelerators have 1 overbarrel slot, bipod slot, and a special slot.
Hyper Kinetic Accelerators have 2 overbarrel slots, 2 bipod slots, and 2 special slots.

I made an entire list of mods that can go into each of those 3 areas, but I'll save that for later. What I want to capitalize on RN is that if we're going to be making the KA's stronger, we should also make the local fauna harder to fight. I have a couple of ideas on how to do this as well.

**Comment by Time-Green** [comment]
I always wanted to make lavaland more challenging, this was a part of it, since well its really freaking cool.
Also I really like to work with datums and I can see alot of applications for them in the KA parts

**Comment by Frostben** [comment]
How about a forward grip instead of a bipod for the range upgrade? A bipod implies that you place the gun on the ground or something like a chest high barricade to give the weapon a stable platform to rest on. And since we don't actually do that here in spessman sim a forward grip would be more sensible

**Comment by LarissaMayrink** [comment]
Make KA's send you flying off in the oposite direction if fired somewhere without grav, because /fun/, and it makes drills usefull during voidmining

**Comment by drderp3635** [comment]
> Make KA's send you flying off in the oposite direction if fired somewhere without grav, because /fun/, and it makes drills usefull during voidmining

that already happens

**Comment by drderp3635** [comment]
make an underbarrel shotgun that can be attached to the ka as an alternate fire. 
probably also make shells designed for fighting lavaland mobs that are also underpowered on station to aviod the shotgun meta taking over completely

**Comment by LarissaMayrink** [comment]
I don't mean push you slightly then send you floating, i mean literally flying off like if someone threw you out of a airlock.
