### ISSUE TITLE
Free Miner ORM not connected

### ISSUE THREAD

**Issue by yellowface7** [yogstation13/Yogstation#2547]
[Round ID]: # ((Freaking forgot to find it)) {IS REPRODUCIBLE!!}

So, I have been playing as a free miner a lot lately and I realized that the orm is not connected to anything. After a few rounds, I decided to ask an admin for help and they were confused too.

[reproduction steps]
Build the orm
insert ore
insert id
you can do the last to steps in any order

And boom, you found the issue!

I remember one time a free miner captain managed to get the points working but I don't understand what they did to get that to work. I believe it may have involved a tech disc.

Either way, shouldn't the orm already be connected once I have constructed it?

**Comment by SomeguyManperson** [comment]
What do you mean by connected? The free miner ORM isn't connected by default to an ore silo, but that shouldn't cause any problems. If the problem is the ores not producing points for your ID, you have to drop them at the input (defaults to the tile north of the ORM) instead of hitting the ORM with the ores.

**Comment by yellowface7** [comment]
Ah. It appears that if you drop an ore on the tile on top of the orm, it gives points. Crates do the same thing if brought to the top tile. I find that really weird. Thank you for clearing that up. I really love playing free miner captain.
