### ISSUE TITLE
Radstorms can be evaded with... lockers.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2621]
OOC: Clonck: also hiding in locker works
OOC: TheMr.FoX: or just sit in a closet
Apparently, everyone knows about bug that hides you from rads and nobody reports.

**Comment by Cruix** [comment]
All Nanotrasen standard-issue lockers are certified faraday cages.

**Comment by Alek2ander** [comment]
![giphy](https://user-images.githubusercontent.com/5909770/30757340-fe2cccbc-9fd6-11e7-8484-9e70da2e6faa.gif)

**Comment by Notamaniac** [comment]
lol make it so only the chefs fridge work

**Comment by 00aquir** [comment]
> All Nanotrasen standard-issue lockers are certified faraday cages.

Meanwhile, the crew gets shocked in enginering hardsuit by tesla without gloves..

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
the suit's gloves are bare metal, the rest is insulated. that's why you have lower but not negated damage

**Comment by Dagdammit** [comment]
Lockers also defend against thermal vision and arcs from the tesla. 

It's a consequence of how lockers work (everything inside a closed locker is effectively shifted into another z-level? I think?), and probably doesn't get fixed because the gameplay effect is more "neat trick" than "ruins game experience."

**Comment by X-TheDark** [comment]
This was fixed by #2639
