### ISSUE TITLE
Plasmaman changing room

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#294]
Simple.

This would be a small-ish room somewhere on the station, probably around dorms; it's public access but is separated by a sequential airlock system, much like the toxins mixing chamber doors.

The inside, obviously, is filled with 100% plasma gas pumped in from an external canister with a few in reverse.

The idea is basically just for a Plasmaman-friendly room where they can peacefully change internals, socialize, etc. The setup also is for simplicity and also allows for fun assassinations via subtly modifying the air supply, ala virology (but even nastier)...

**Comment by Super3222** [comment]
Basically a free greentext room for traitors? Communication is key in the game, so if you want something like plasma as a plasmaman TO LIVE, people should get their sticks out of their asses and give it to you.

**Comment by ParagonPrime** [comment]
Not really. It's just... a room filled with plasma. The supply is locked behind an atmos-access door.

It's pretty niche if all you wanna do with it is murder.

**Comment by Super3222** [comment]
I mean, it makes it much easier for traitors since no one's going to protect the plasmatanks used for the plasma-man room. This creates an easy shortcut to gaining an entire tank full of plasma to greentext with.

Compared to the engineering division, which in atmospherics you'd need to work for it while the AI may become suspicious of your actions and in engineering you'd need to get the secure storage open in front of other people. Toxins of course, is the easiest place to get plasma, and is super easy if you have the proper access for it. If you don't, you're going to get caught.

With a giant room pumping in plasma which plasmapeople aren't going to use 100% of the time and sometimes not even care about, it'd be too easy to steal plasma. I honestly doubt many plasmapeople will even use this in the first place, so we'd just have an entire room full of plasma for no reason.

So say we don't use any tanks to pump in plasma with, but instead those large plasma ones which are unmovable, you can't take anything from them, and are only good for pumping out (like the one in the incinerator). Then there'd be no trouble with this. My fear is that it's going to be practically useless because in that instance plasmapeople aren't going to have any way to get plasma unless they bring an air pump with them. Meaning the only thing left to do is socialize and be happy that you don't have to use your internals.

So say that none of the things I wrote before happen, I still see both doors getting bolted open/forced open somehow, plasma spilling out of the room, and lots of plasmafire. Whether it's from security chasing a plasmaperson who dove into there, someone setting a dominator there intentionally, a plasmaperson accidentally setting off a spark and ruining the entire thing for everyone, etc etc. It'd be bad to have this thing on station.

The idea of it is nice in theory though for a plasmaperson chill zone.

**Comment by Greatbigben** [comment]
i agree with super, nice to think about but bad in practical
