### ISSUE TITLE
Missing texture for ninja mask

### ISSUE THREAD

**Issue by AAAbattery** [yogstation13/yogstation#303]
When you spawn as a ninja it appears that you are not wearing a mask at all. Instead of the white mask with red eyes it is simply skin color with normal eyes. Not sure if this is fixed by taking it off and putting it on again, did not test.

**Comment by timkoster1** [comment]
@Stealthkibbler

**Comment by Stealthkibbler** [comment]
@timkoster1 This is probably because the default ninja mask doesn't use the color variations for when the ninja intializes his suit, I checked the files and it only has S_Ninja, not S_ninjan, all the other ninja Dmis have Ninjan since thats what the ninja sprite changes to when it initializes.

This will be fixed when this gets pushed #291 which not only replaces the old sprites but adds in a Ninjan sprite for the mask.

**Comment by Stealthkibbler** [comment]
#291 wasn't pushed however another one that was merged with the same changes along with katana changes was. This should be fixed next update.

**Comment by Greatbigben** [comment]
update?
