### ISSUE TITLE
Reduce Goliath tendril stun times

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#310]
They seem a lot longer than previously, on the mining asteroid.

One hit from a tendril = instant GG unless you have healing. If there are any other mobs around, GGGGGGG.

Solution is simple: just reduce the stun time by 1-2 seconds.

Quality of life will be boosted immensely.

**Comment by Super3222** [comment]
Everything is meant to kill you on lavaland, tendrils are no exception. Their long stun is good, because if you're too close then you get beaten to death. That's the entire mechanic of goliaths. Otherwise, goliaths will be just as easy as beating on the asteroid.

However if you're on your feet, continually running, and avoiding other hostile mobs nearby then nothing wrong will happen. The only reason you'd be stunned by a tendril is if you're clumsy, backed against a wall, or you aren't being agile. Then it's your own fault for getting pummeled to death.

**Comment by ParagonPrime** [comment]
Often it's when you're in an enclosed area (as you are often forced to be) or there are multiple goliaths.

One second reduction will make them less deadly- but perhaps their melee/tendril damage can be buffed, so that you can get pummeled but actually escape rather than just creating stunlock cheese.

**Comment by FluffySurvivor** [comment]
While goliaths have some defined counterplay, it really needs some nerfing for easier manuevering.

**Comment by ParagonPrime** [comment]
Either decrease the stun time or increase the time from tendril appearance to actual stun

**Comment by Super3222** [comment]
> increase the time from tendril appearance to actual stun

No. That's a terrible suggestion, and they'd be as easy to defeat as the ones on the asteriod.

> decrease the stun time or increase

That's ridicolous, but if you want to /really/ decrease it very slightly (like the literal -1 stun time you proposed) then I could go for that. The thing is, these Goliaths are much stronger and deadlier then the ones on the asteriod. Which was always a good thing, because now even people who are getting use to lavaland even have a hard time fighting them. **They are no longer a joke.**

I don't want to nerf everything the unexplored and dangerous lavaland has to offer otherwise it will definitely come off as, "/tg/ players can take, but yog players can't!".

Don't get me wrong, I've dealt with goliath hell. I once came close to capturing a nercopolis crate, when a random goliath out of my vision got onto me, and we all fell into a chasm.

Also I want to clear something up. One hit from a tendril will definitely be GG because that's how goliaths work. They tangle up their target and pummel them to death. Otherwise, weaker tendril stun  s will allow any clumsy miner could beat a goliath who doesn't know how that they have to be agile and quick on their feet.

Goliaths should not be easy to beat.

**Comment by SeikoTheSeal** [comment]
>They seem a lot longer than previously, on the mining asteroid.

Haha, man did you even play mining before tendrils were nerfed into the ground?

**Comment by AdamElTablawy** [comment]
otherwise no this isn't happening theyr'e staying unnerfed

**Comment by SeikoTheSeal** [comment]
>make tentacles trip people who walk over them

**Comment by FluffySurvivor** [comment]
Look, the purpose of lavaland is to have a fun, cool and dangerous adventure in the search for neat loot. I shouldn't have to turn into a 300 APM machine only to stay alive more than 2 minutes. If players had wanted hardcore micro they would just play ranked Starcraft. 

For the pace of the game, the 2(?) seconds delay is extremely small.

**Comment by SeikoTheSeal** [comment]
>Look, the purpose of lavaland is to have a fun and dangerous adventure in the search for neat loot.

Its exactly that currently.

>I shouldn't have to turn into a 300 APM machine only to stay alive more than 2 minutes by dodging goliath tentacle hentai.

Holy shit that mob actually requires a bit of thinking to beat instead of being a charge>beat to death gear check! What madman would require 2d spessmans players to actually use their brains!

Stand still. Fire two KA shots. Walk backwards a tile. Fire two more KA shots. Walk backwards. Notice that goliaths eyes turned red. Stand still and prepare to dodge tentacles. As tentacles appear, walk into the tentacle free spot, his tentacles never block all directions/just fucking run in any direction you wan't becouse goliaths were nerfed into the ground and you can freely run over their tentacles without tripping.

Smh.

**Comment by AdamElTablawy** [comment]
you can melee it just by hitting it twice with a spear, backing off, and coming back

**Comment by FluffySurvivor** [comment]
Yeah but there is usually at least a basilisk that slows you or some other mob.

**Comment by SeikoTheSeal** [comment]
Can we have "i ded" and "git gud" tags added for this issue?

**Comment by Stealthkibbler** [comment]
The old Goliath tendril was actually a lot harder but required you to think when moving and pause, if you walked into a tendril you got snared, that's why the goliath snares in a T shape, because that one area where a tendril doesnt pop up use to be the area where you use to walk out of to avoid getting stunned. Fast forward a bunch of scrubs whining about being incapable of understanding simple mob mechanics that are commonplace in just about any game with monsters and you got the nerfed tentacles that only stunned if you were standing on one when the duration ended.

"AAAAAAAA GOLIATH STUNS FOR TOO LONG AAAAAA" 
Stimpacks reduce goliath stun for 2 seconds and make watchers slow you down a lot less, literally the main reason why they exist is to mitigate the goliath stuns, as if miners didnt have it easier enough since they now spawn with KAs, back in my day you had to use a coupon or points to get that shit.

> Look, the purpose of lavaland is to have a fun and dangerous adventure in the search for neat loot. I shouldn't have to turn into a 300 APM machine only to stay alive more than 2 minutes by dodging goliath tentacle hentai. If players had wanted hardcore micro they would just play ranked Starcraft.
> 
>  For the pace of the game, the 2(?) seconds delay is extremely small.

your average goliath counterplay
![](http://65.media.tumblr.com/tumblr_lltasw5eu51qhiioh.gif)

smh, scrubs everywhere, l2 miner, l2 KA, l2 kite, if you scrubs cant even defeat the most static mob in the entire game then I cant wait until people start bitching about marrow weavers lmao.

> Yeah but there is usually at least a basilisk that slows you or some other mob.

watchers literally have like a 2 tile aggro range, you have to be lolrunning carelessly to actually manage to aggro one on accident.

**Comment by ParagonPrime** [comment]
I have managed to do the thing known as "gitting gud".

Even I can see this is absolutely pointless and ridiculous now.

GG
