### ISSUE TITLE
Storage implants are not shown on the surgery console

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation#315]
1. Put dude with storage implant on surgery table.
2. Nothing shown.
3. He goes free.
4. Ez greentext.

**Comment by GrayRachnid** [comment]
Hey man if ur gonna metagame metagame hardcore, cremate him and if items drop then he's a traitor ez.

**Comment by Cruix** [comment]
You have to take an implant of the same type out and scan it before the console will recognize it.

**Comment by FluffySurvivor** [comment]
>You have to take an implant of the same type out and scan it before the console will recognize it.

scan it with what

**Comment by Cruix** [comment]
With the surgery computer

**Comment by Super3222** [comment]
You use surgery to take out their storage implant, HOLDING an implant case otherwise the implant will be lost. Then you put the implant case in the operating computer, switch modes, and then scan it.

Therefore, whenever someone gets on top of the surgery table, you'll be able to see their storage implant.

However, that does sound like a good counter for storage implants, so I'll take it into consideration. I know this was a bug report, but then again it isn't exactly a bug. I could use some thoughts on this.

**Comment by FluffySurvivor** [comment]
So hold on you can't instantly check someone's implants when they are on the table? 
B A D

**Comment by Stealthkibbler** [comment]
Problem is Super, there's no way for anyone to know that, I too have scanned people on the op table to find they dont have a implant after they literally emagged through brig after being perma'd

It shouldn't be an overly complicated thing, should be simple and easy not some convoluted shit wherein you have to present the box, because chances are, the traitor has probably disposed of the box, then what?

**Comment by Super3222** [comment]
That's why I'm taking into consideration of what Fluffy thought was a bug. Making what's "inside" of people's bluespace pockets show up on operating table computers.

Not sure what you mean by presenting any sort of box. If you perma someone, leave them with absolutely nothing to break out with, and somehow they manage, it's allowed on our server to try to remove their storage implant (from what I've talked about with an admin).

My only fear is that this'll become the servers "new meta" where security stacks traitors on top of surgery tables just to see if they bought a storage implant.

**Comment by FluffySurvivor** [comment]
The traitor I caught was stupid enough to leave the implant box in the bathroom, and his prints were the only prints I found.

**Comment by ShadowDeath6** [comment]
just make it so every traitor implant comes up as the same thing or some shit so they can't immediately say storage implant

**Comment by Greatbigben** [comment]
the meta, and you can break out of perma with nothing but coffee and donk pockets, both of which are available in Perma. Unless you seen the item magically disappear after he used it then there is no logical reason for you to check unless meta. If anything just remove the implant till further notice XD

**Comment by oisin100** [comment]
This is intended.
