### ISSUE TITLE
Free miner mech wreck won't contain enough parts to build another mech

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#3372]
I've had multiple complaints about this, probably has something to do with the wreckage still rolling rods/plasteel/metal sheets

**Comment by ktstudios2000** [comment]
This might be an intentional design with a misleading description for the free miners.

`	for(var/i = 0; i < 2; i++)`
`		if(parts.len && prob(40))`
`			var/part = pick(parts)`
`			welder_salvage += part`
`			parts -= part`

When you use a welder on the wreckage of a mech, it collects from a pool of items. Each wreckage, upon creation, goes through the above loop twice, with a 40% probability each time of adding to that pool, which currently consists of plasteel, wires, and rods. It'd be a very easy to fix, but I just need confirmation that it is a bug before I create the relevant PR.

**Comment by Ktlwjec** [comment]
I'd hope this would be intentional

**Comment by ThatLing** [comment]
Why wouldn't this be intentional? Ofcourse you aren't getting all your parts back.

**Comment by ktstudios2000** [comment]
The description for the free miner engineer states:
>After years of saving, you finally have just enough parts to put your own mech together. Salvage the wreckage with a welder and a crowbar to get them.

If you aren't expected to receive all the parts needed for the Ripley mech from salvaging, the description for the free miner engineer either needs to be changed, or additional Ripley parts be added to the free miner ship in order to allow for the Ripley's assembly (it currently only spawns with a torso).

**Comment by Ktlwjec** [comment]
ok I'll change the desc

**Comment by SomeguyManperson** [comment]
The free-miner mech pre-wreckage fix(#3298) was set to drop every part required to finish the mech frame at the charger. The wreckage is specifically called ripley/loaded_ripley instead of being a vanilla wreck
I'm assuming it's due to the wreckage fix mainly because nothing else has touched the free miner wreckage's drops

Without the full mech the engineer can't do much aside from twiddling their thumbs or nabbing a hardsuit before another crewman does, since the miners don't get an exofab and can't otherwise attain mech parts without visiting the station or derelict

**Comment by Toskin** [comment]
Same here, and I, instead of limbs, got dozen 30-piece cable coils.
![image](https://user-images.githubusercontent.com/8083413/50376657-6c6f7d00-0610-11e9-885b-8e92f79524d2.png)
