### ISSUE TITLE
Blueshield and security paramedic

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#410]
Something i wanted to add for a while but never bothered to learn how2code untill now.

Give opinions if those two jobs have a place on the server or i shouldn't really bother with adding them.

http://nanotrasen.se/wiki/index.php/Blueshield_Officer

Job itself is incredibly fun when played the way its meant to be, but i'm bit worried that he'd just end up being used by people to validhunt / act like an officer instead of being bodyguard for heads/their assistant.

http://nanotrasen.se/wiki/index.php/Brig_Physician

>removing inter-dependence among departments.

**Comment by Kmc2000** [comment]
@seikotheseal

I've always wanted blueshields to be added
Brig paramedic is meh, making medical even more dull is a bad thing.

I was actually thinking about making some swat sprites, would they be welcome for the blueshield?

**Comment by SeikoTheSeal** [comment]
If you want to sprite some original sprites for it then it would be cool. i wouldn't have to steal Paradise ones.

**Comment by Super3222** [comment]
For years I've been telling everyone that we need some sort of brig medic

It's just that our map is so tight that'd it take some levelheaded mapping to move everything back a few spaces to install a legit office for one in our brig.

**Comment by SeikoTheSeal** [comment]
I am planning to remap brig once/if i start working on this.

**Comment by Kmc2000** [comment]
Working on the sprites

**Comment by Super3222** [comment]
Blueshield Officers wouldn't be bad, as LONG AS THEY ONLY PROTECT COMMAND. And when I say that, I mean hugging the Captain 24/7.

I feel like people are most likely to work as officers still as blueshield.

**Comment by SeikoTheSeal** [comment]
Questions:

Death alarms Y/N?

What weapons/equipment should blueshield have?

Baton/telebaton, pepper spray, flash, pair of cuffs, some ranged weapon, anything else?

For a ranged weapon, what kind? Personally, i wouldn't want to give them ranged stuns, as thats the shit that makes people go around and act like sec. Instead, give them a lethal only sidearm with only a little spare ammo at roundstart, one that would take some effort for them to get more for. That means it would need to be a ballistic gun, which would create balance issues with nuclear emergency/traitors, or create an energy sidearm using magazines simmilar to CTF guns.

**Comment by ParagonPrime** [comment]
Maybe give Blueshield officers a WT-550 as their ranged weapon. Cargo interdependence woohoo-
Shouldn't be too unbalanced with nukies. Eshields still have a decentish chance of blocking bullets and whatever the Nukies are carrying should be superior to the WT-550 anyways (20 damage befor armour reduction, and nukies have strong armour)

Blueshield should have two or three job openings. And yes, of course death implants.

**Comment by ToGWtF** [comment]
Make the Blueshield a random event and spawn it from observers/dead players with a prompt. That way you don't ALWAYS have that one player who's entire job is to powergame harder than you. Basically mini-ERT event.

**Comment by X-TheDark** [comment]
Or maybe make it require X number/percent of heads to be dead before being able to be spawned. Just as ToGWtF said, basically a one/two-man-ERT with mission "Protect remaining heads, as we detect via our crew monitor that they are dropping like flies".

**Comment by SeikoTheSeal** [comment]
Eh, i would prefer it to be a normal job honestly (totally not becouse i fucking love blueshield and want to play it over and over and over every round). If it was a random event that came late into a round, you wouldn't really have time to create a bond with the people you are tasked with protecting and assisting, and you'd end up like a weaker ERT defending some fucks you don't know, don't care about.

**Comment by ParagonPrime** [comment]
It should be a standard station job.

It doesn't matter how robust the Blueshield is, because they should be hawked even more closely than normal Security staff; if they abandon their duties guarding heads, then _boink them_.

They're not comparable to ERT since they're supposed to stay in one place- with the head they choose.

**Comment by Kmc2000** [comment]
![](https://i.gyazo.com/88a8053786b27c3313460c50554140c7.png)

Full gear


![](https://i.gyazo.com/80e502fc9db37102a23203ce8ad9d501.png)

Armour and suit


![](https://i.gyazo.com/0f721a588060d84247dd490a1d1bb22d.png)

Jumpsuit


^ Potential sprites i've cooked up

**Comment by SeikoTheSeal** [comment]
Bob pls give also a scaled down images like they would appear in game ;_;

**Comment by Kmc2000** [comment]
![](https://i.gyazo.com/f8ff30e3e2767d2cdaa086dc8dfb1437.png)

![](https://i.gyazo.com/1b378aa67e1b23a216947daa4dd91391.png)

![](https://i.gyazo.com/17832734fafb87aa68a0c462ad71f8af.png)

**Comment by ParagonPrime** [comment]
ehhhhh

i sorta like the original version better

make them look like secret service agents in real life (formal suit [with built-in armour], laceup shoes, sunglasses) plus an armoured vest with a blue shield symbol.

that would be badass

**Comment by SeikoTheSeal** [comment]
The armor looks and helmet look very much like riot gear, which i don't think fits a bodyguard. Paragons vision of it sounds actually pretty fucking cool. Could probably always leave a few alt uniforms in a spare locker for players to play dress up and pick the outfit that fits their own preferences.

**Comment by ParagonPrime** [comment]
maybe blueshields could have a special "lightweight plate armour" which is like a slightly lighter (and thus less movement-restricting) but less protective riot suit

it would look like a bunch of ceramic plates, shoulder/elbow/knee guards and etc. strapped on the suit rather than a single piece of armour, which would be BADASS

**Comment by SeikoTheSeal** [comment]
Riot suit have no slowdown for a good while now.

**Comment by ParagonPrime** [comment]
huh

scrap that then

unless we make it frowned upon to wear it when not necessary, like security hardsuits

**Comment by SeikoTheSeal** [comment]
Also why is this tagged feature request.

Its more like, feedback request.

**Comment by ToGWtF** [comment]
Perfect use for old mechanic we added but never found a use for : Code Red restricted armory. Blueshield spawns with a normal black suit (With minor armor like sec) and a vest with the blue symbol, but has a "Power armor" sort of deal in his office using your sprite that can only be used when heads call Red Alert. Super slowdown, un-draggable (So no using him as a meatshield while he fires behind him), but heavily armored. He is literally a supersoldier NT sent to protect their assets, compared to a HoS that's virtually a mallcop. On death, it gibs the suit and whoever is inside so no stealing it and no reviving your blueshield 

Other idea : His power armor can only be accesses via the Captain sending an ERT message and it being bluespaced in. Only the Captain has authorization to request it, so no traitor CMO-Acting-Captain getting a free supersoldier teammate. Good for sending loyalists a bit of support without sending in a full ERT to upset the balance of the round.

idk throwing shit out there

**Comment by ParagonPrime** [comment]
honestly i also just don't like the power armour sprite either

**Comment by FluffySurvivor** [comment]
How to encourage blueshields doing their jobs: add a greentextable objective "Protect X head(s) ", like the antag obj

**Comment by SeikoTheSeal** [comment]
Thats actually a quite good idea. I'll have a look and see how objectives and stuff works.

**Comment by ParagonPrime** [comment]
fluffy
i love you

**Comment by X-TheDark** [comment]
I'm really afraid this will be played solely to validhunt and add additional problems for admins to enforce (so the guy doesn't play security/guy stays with the heads and doesn't validhunt,powergame/etc).

**Comment by Super3222** [comment]
Blueshield Agents/Officers will be hard to implement since Security Officers already are assigned to divisions to "guard" them (heads included).

My suggestion is to make only one position for the blueshield agent, and their mission is to protect  and obey command personel, but the highest chain of command is their first priority (sort of like how knights work in other games, where their only goal is to stay by the captains side almost 24/7).

So it'd go like: Captain -> HoP -> HoS -> CE -> RD -> CMO

They also wouldn't have the same amount of access as an officer. For instance, they'd lack maintenance access so they have no reason to run around in maintenance valid hunting.

Possibly a 'blueshield access card' which they can use on head airlocks (HoP office, CE office, HoS office, Captains office, you get the jest) that will send an alert to the correspondent head's PDA asking if they want to open that airlock.

A blue shield agent would never be able to be an antag, not even blob because to be by an honorary agent of the blueshield faction, they require their agents to bend over for bacterial or yeast infection checking.

Some of the things Paradise has for these guys are pretty damn neat, like the switchable stun/laser pistol. Or maybe we could think up a few things our selves to make them more agenty, while trying to keep them away from validhuntery.

**Comment by FluffySurvivor** [comment]
it's nothing dramatic if blueshields choose to validhunt,  just encourage protecting heads and buff traitors with something

**Comment by ParagonPrime** [comment]
No, blueshields should NOT be validhunting.

Their (main) equipment should be a stunbaton, extendable riot shield, and WT-550. The best way to discourage Shieldcurity is by giving them a versatile lethal-only long range weapon that can only be resupplied through Cargo's cooperation, so they can't stop the clown for B&E without being smacked over the head with space law.

It should come down to, "if you see a crime that doesn't directly endanger a head, do not attempt to interfere, even if it's a murder- contact security."

Obviously, the Blueshield would have access to Security and Command frequencies and it would be up to the head they are assigned to to provide a departmental encryption key, though I can't see much reason for using it.

Blueshields should be able to choose which head to protect (so you don't get bored guarding the Captain EVERY SINGLE ROUND) until there is a confirmed threat to a particular head, in which case Chain of Command kicks in. Though Blueshields should be discouraged from protecting the HoS on grounds of "he can protect himself" to prevent validhunting (reasoning being "WELL THIS CRIMINAL THE HOS IS HUNTING COULD HURT THE HOS")

The special "PDA-to-access" ID seems a bit annoying and overly complicated, and it might be worth just giving them direct access to the Head offices (BUT keeping separate the access to lockers- that'll be an interesting coding task). Though if you insist on having it, it could set the framework for an interesting function of having certain airlocks send PDA messages when accessed.

I think Blueshield will be an extremely fun role, especially on Revolution and Nukeops. But don't choke it too much.

**Comment by Super3222** [comment]
I originally thought of giving them access to head offices, but that'd give them access to their lockers. Instead of being lazy and just separating that access into two separate access levels, it'd be fun to give them something cool to utilize.

Blueshields aren't officers, they are bodyguards. They do not hunt, they protect. Like Paragon says. Validhunting IS a big deal Fluffy because it is their JOB to be a human shield and NOT take security's job.

We have room to imaginate and shoot ideas at each other, I don't think we should just take Paradise's creation and practically copy and paste it onto our code source. But I agree with Paragon though, we shouldn't choke it too much.

I also don't see whitelisting necessary because then players won't be able to experiment or even try out. them. Restricting it until a player age of 15+ maybe sounds good.

**Comment by ParagonPrime** [comment]
Maybe we could code a specific item, the Blueshield Identifier.

Would be a tiny item that is literally the same as an ID, except it can ONLY be used for opening airlocks. And the only access it gets is the Head airlocks and Bridge.

Roundabout solution but it works.

**Comment by FluffySurvivor** [comment]
Give a clown plants and he will do botany. 
Give a cargotech medical gear and he will heal people. 
Give an assistant a stunbaton and he will act security. 

Of course, that's what they at least tend to do. 

You can't expect someone with a juicy rifle and better equipment than an officer to just ignore a murderer. 

Case 1: If players find sticking with a head more entertaining than validhunting, then sure they will do their intended job, that's perfect. 

Case 2: However, if they don't do their intended job because it's not satisfying, they will find entertainment somewhere else causing balance problems and such. 
Add fear of bans and admin intervention and the whole deal becomes a failure. 

The job must be made interesting and fun enough so case 1 occurs. 

>Blueshields aren't officers, they are bodyguards. They do not hunt, they protect. 

What they are and what they do is decided by the players that play the damn game.

**Comment by Super3222** [comment]
My point:

A blueshield officer standing around, protecting heads, making sure the area (where the head is located) is secure, and all in all making the heads feel special is GOOD.

If a blueshield officer during a normal round goes out of their way to get a forensic scanner when there's been a murder, do police work, and discover a criminal that has NOTHING to do with the heads or their safety. That's validhunting and what we want to prevent. We have enough security jobs and positions for that.

They are hired bodyguard. They are not officers. This is the concept Paradise created.
"Duties: Act as a bodyguard and adviser for Command and CentCom VIPs." -- Job Information
"Apprehension of criminals is their job, not yours, and your handcuffs should be used to neutralize threats to the Command staff." -- Relation with Security
Going into exhibit 2 is a problem. 

I get the situations where there's a known traitor near a head, and a blueshield wants to take them out / incapacitate them. If they see a murder take place, they should be able to fucking go ahead and fire at them. If a -known- murderer passes by them while they're on duty, then that's fine to take them down. As long as they are visible threats to command staff. It's completely fine, and not what I'm against.

Other Text:

Although I see where you're coming from, this job isn't that flexible at all and requires you to play on a level of patience and reply on others during security measures.

You aren't wrong Fluffy and in all honestly, this is literally a half rp job.
To port it over correctly would require that impossible style of 'don't be a vigilante, but here take all of this sec gear'. And that's because it comes from a literal roleplay server, where this is probably considered normal. So to bring it to our no rp - low rp server will be undeniably difficult.

Shitty Conclusion:

There'd almost be no point towards blueshields tbh. In the end, it's nothing we could handle at the moment (low rp standards am i right) or even control which is what they require.

So say we go down this path of letting them validhunt.

Letting them act as security will create another stupid, pointless security position in the end, and that's the very last thing we need. They'd literally be another bland security officer basically told to stand by the heads which is something we don't need.

Dressing them up in blue and giving them people to protect won't change the fact that they're still general security, allowed to act as security, and pursue criminals. I can do the same thing as a security officer and I don't need an advanced stun revolver to do it.

**Comment by ParagonPrime** [comment]
No, it's really fucking simple.

Port them. If people validhunt with them, jobban them on the fucking spot.

It's really that fucking simple and hopefully people will get the picture really quickly.

**Comment by FluffySurvivor** [comment]
>If people validhunt with them, jobban them on the fucking spot.

If we need bans to make a "feature" work, then it's not a feature and it doesn't work.

**Comment by ParagonPrime** [comment]
I don't see how this is any different to banning shitty Captains or AIs.

If you step outside your job's parameters, do something stupid and reckless, disobey your laws as AI, or generally act incompetent, sooner or later you WILL be banned for it.

**Comment by Robertruler77** [comment]
God, can I play medical staff in the brig without having to go through a 11 step process that might fuck up at any point yet? Medical in the brig is a fun little 'Build relationships' thing I love doing, cause you can badmouth your team to people who get your complaints, cause they have them. 

Dumb tangent aside, I'm all for a brig medic, but Blueshield? On the fence, but sitting on the 'add them' side. 

> If we need bans to make a "feature" work, then it's not a feature and it doesn't work. 

Fluffy, we'd ban every role with that logic. But, yes, it takes a certain skill in patience to serve and protect heads. I don't know if it would really be worth it as the BG now becomes the bigger target (however medical might not always be the 'birthplace of trouble' now) but a bigger threat. Just something to note.

**Comment by ParagonPrime** [comment]
Let's re-awaken the discussion.

Or not.

Let's also just implement this already and see how it goes :^)

**Comment by Super3222** [comment]
Bluehield or not to blueshield? That is the question

**Comment by SeikoTheSeal** [comment]
Well, Asv had them ready a week or two ago already.

**Comment by Greatbigben** [comment]
Firmly against blue sheilds, at this point it would be another valid hunting job. Against brig medical also, one department shouldn't be self sufficient. It will literally invite turtle playstyles when rev and gangs pop up.

**Comment by Alek2ander** [comment]
Adding blueshield will remove all-access clown bodyguard memes. :-1:

Not entirely against brig medics, but it's more interesting to have security invite an actual medical doctor and give them a gun and access. Department ID consoles exist for this very reason.

**Comment by ParagonPrime** [comment]
Guys, how the fuck would blueshield be a validhunt job?

WHAT POSSIBLE ASPECT OF BLUESHIELDS IS VALIDHUNTY

THE ENTIRE POINT IS THAT THEY GET BAN'T IF THEY AREN'T CONSTANTLY HUGGING THEIR HEAD.

**Comment by Greatbigben** [comment]
The admin team at this moment is unable to follow one guy around for the whole round. Our server is (low rp) Blue sheild is a rp job. At this time it would be quite frankly insane to implement this. Maybe in the future it would be better.

**Comment by utahclock** [comment]
hardy stated in annoucements we are med rp as of now.

**Comment by Greatbigben** [comment]
Most of the player base doesn't know what that is.  Until it's properly enforced, it's all smoke and mirrors.

**Comment by EMT321** [comment]
Can we close this if it is not coming to pass? Doesn't seem necessary at the current time.
