### ISSUE TITLE
Disable lavaland roles for observers

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#439]
You don't get to fuck off for your free asswalker antag.

Disable all ghost roles-excluding pai and drone and posibrain-for anyone who clicks the observe button or who dies in the first 5-10 minutes to a suicide.

No more suiciding cause you want ashwalker/golem/holoparashit.

**Comment by timkoster1** [comment]
Some coder messed with the lavaland values, all ghost roles are gone

**Comment by SeikoTheSeal** [comment]
How bout you fuck off.

**Comment by fizzle7** [comment]
Uhhhh, tag meme issue?

**Comment by Bekons** [comment]
So you're saying is, people don't play how you want, so that other way of play should be removed?

**Comment by Super3222** [comment]
> Some coder messed with the lavaland values, all ghost roles are gone

We haven't updated for 2+ weeks.

**Comment by AdamElTablawy** [comment]
Yeah no, i'm saying antag fishing is bannable anyway, make my job easier

**Comment by AdamElTablawy** [comment]
Also ghost roles are for dead people not observers-korphaeron's words

Hence this is the creator's intent

**Comment by fizzle7** [comment]
> Hence this is the creator's intent
yaoming.jaypeg
If everything went according to the creator's intent this game would probably be pretty cool.
You realise though that asswalkers and golems being antags are also the creator's intent right? So pick a side...
We could make the ghost roles be only for dead people that have died after playing for X amount of time, sure, but this makes it so that you only have 5 minutes of gameplay before some idiot calls the shuttle cause he slipped on a wet tile. Or you can play 10 rounds and never find ashwalker cause it's random.
Roles are made to be played, if the player is good, both observers and dead players can get to play because both ashwalkers and golems can increase their numbers. If the player is bad it doesn't matter if you're a dead player or observer cause you won't get to do it if they hoard all the spawners. And it hasn't become a problem where people observe just to get a lavaland role and occupy all of them. Should probably run statistics before deciding.

**Comment by AdamElTablawy** [comment]
Golems are nonantags @fizzle7

Ashwalkers and prisoners are antags. Ashwalkers can murderbone, prisoners can do shit related to their crime reason.

Pod people and golems are nonhostile unless provoked and no 'one human stole my med supplies' doesnt mean you can singbomb the station.

Vetrenarians are nonantags, but can attack people for animal cruelty (no killing)

**Comment by AdamElTablawy** [comment]
Anyway, all this stuff is just making my job easier anyway. I can just delete the ghost roles myself manually if they're being abused, but ashwalkers and golems can make more of themselves so i'm fine with observers picking em.

**Comment by ShadowDeath6** [comment]
>be miner
find ashwalker nest within 10 minutes
break it because nobody dies in 10 minutes unless the antag that kills them is super good or they suck ass

**Comment by Stealthkibbler** [comment]
imho most the ghost roles that cant reproduce are pretty garbage anyway, reproduction roles generally have that feeling of unity and teamwork, other roles are just people fucking off into the wastes and dying, for example the animal hospital serves a purpose for roleplay with the cow and the rat, but most people just fuck off into the wastes or die since there isnt anything to actually do in the animal hospital. 

Same can be said for beach bums, only fun I had as a beach bum was overdosing on spray tan and surviving in the wastes with another beach bum, we constantly would help eachothers, calling ourselves and everything bro dudes and gnarly. It was quite a chuckle but the roles just didnt serve their intended purpose and running off to the station as these roles is quite boring unless you're a golem or walker that needs resources from the station.

**Comment by ParagonPrime** [comment]
The only two roles that have gameplay outside "fuck off to the station" is golems and asswalkers, and the latter's endgame is actually to fuck off to the station anyway.

but that's beside the point-

The core of the issue is fucking retarded

why the fuck should we be preventing people from choosing ghost roles if they want to

i mean, even when asswalkers DO spawn, which is rare, i barely ever see people actually choose to become them rather than just play normally

**Comment by EMT321** [comment]
@Adameltablawy @Cruix Can this issue be resolved and/or closed?
