### ISSUE TITLE
Broken virus stats

### ISSUE THREAD

**Issue by Graporb13** [yogstation13/Yogstation#4409]
Sorry if this should be posted to tg's github, but this is where I was playing.

So, I've been playing virology lots today. When I started making viruses that were supposed to be airborne or happened to be resistant, it was as if the values were sometimes set to 1 or 0 instead of what the PANDEMIC claimed they were. I'm not sure whether stage speed was effected, and stealth seemed to work.

## Reproduction:

These are the exact viruses I used, and the results:

viral adaptation, evolution accel, cough (neutered), itch (neutered), and starlight condensation
stats: stealth -1, resistance 5, stage speed 6, trans 7
this was curable with orange juice and seemed to only be blood-borne

itching (neutered), fever (neutered), cough (neutered), vitiligo (neutered), and tissue hydration
stats: stealth 1, resistance 8, stage speed 10, trans 5
while i don't remember the cure i believe the resistance worked in this case, though it was still only blood-borne

**Comment by nesisknesis** [comment]
Not a bug.

Transmission is calculated with 'disease's transmission - amount of symptoms'; this means more symptoms, less transmission due to no. of symptoms deducting from it. In your case: 7 trans. - 5 symp.= 2 Actual Transmission. 2 or less is blood, 3 is fluid contact, 4 is skin contact, 5 is airbone. 

Adding sneezing will effectively make your virus airborne, but displays a message. Other ways you can spread it is through contaminating food with your virus, or straight up shooting syringes at people with the syringe gun.
