### ISSUE TITLE
Nerf ninja

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#443]
Ninja OP

Change the invisibility to be more like a fade instead so you can kinda see it, but not really.

**Comment by SeikoTheSeal** [comment]
Or make it so that ninja actually becomes visable after attacking someone. That would make it bit more healthy.

**Comment by Super3222** [comment]
> Ninjas
> balance

u crazy

**Comment by SeikoTheSeal** [comment]
There is being strong, and there is being unkillable as long as you have more than two braincells.

**Comment by AdamElTablawy** [comment]
So 90% of antags?

(Ops, wiz, blob, xenu, ling, cultist, cock cultist)

**Comment by FluffySurvivor** [comment]
none of those antags can kill you while invisible

**Comment by Jc1469** [comment]
I don't see the point in nerfing something that you barely ever see as it is.  
A good idea would be to make it so people have to state what round made them salty to cause these requests.

**Comment by SeikoTheSeal** [comment]
>I don't see the point in nerfing something that you barely ever see as it is.

Event weights were changed, seeing shit like swarmers or ninja is helluva lot more common than it used to be.

**Comment by EMT321** [comment]
Their sabers also deflect bullets. Buckshot twice at close range? Lolnope

**Comment by Stealthkibbler** [comment]
I discussed this with KMC, Ninja really needs a fade cloak like the predators from CM wherein its cloak shimmers whenever it moves but is completely undetectable while standing still. Attacking would also break said cloak and being attack as-well.

We watched a single round where bekons as ninja managed to kill almost the entire crew by just being permenantly invisible with power cells. The invisibility is, as it stands, broken in terms of balance and is extremely unhealthy from a gameplay perspective to be in the game.

**Comment by Stealthkibbler** [comment]
/code/modules/ninja/n_suit_verbs/ninja_stealth.dm

that's the location of the ninja stealth code, if you understand how code works its super simple to understand and Im pretty sure anyone can see whats wrong with it without even looking at the code.

/obj/item/clothing/suit/space/space_ninja/proc/toggle_stealth()
	var/mob/living/carbon/human/U = affecting
	if(!U)
		return
	if(s_active)
		cancel_stealth()
	else
		if(cell.charge <= 0)
			U << "<span class='warning'>You don't have enough power to enable Stealth!</span>"
			return
		s_active=!s_active
		animate(U, alpha = 0,time = 15)
		U.visible_message("<span class='warning'>[U.name] vanishes into thin air!</span>", \
						"<span class='notice'>You are now invisible to normal detection.</span>")
	return


/obj/item/clothing/suit/space/space_ninja/proc/cancel_stealth()
	var/mob/living/carbon/human/U = affecting
	if(!U)
		return 0
	if(s_active)
		s_active=!s_active
		animate(U, alpha = 255, time = 15)
		U.visible_message("<span class='warning'>[U.name] appears from thin air!</span>", \
						"<span class='notice'>You are now visible.</span>")
		return 1
	return 0

When stealthed it changes the characters color alpha to 0, which obviously makes them completely invisible, when unstealthed vice versa. The idea would be to make it so that when the ninja moves a tile or is attacked or attacks his color alpha changes to a value which makes him somewhat visible, by not moving or attacking he reverts to being completely invisible.

it sounds like the easiest and simplest way to define it, if I knew how to actually code it, I would, but someone else could probably figure it out pretty easily on their own I think.
