### ISSUE TITLE
Gas station clerk and vendors

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#4526]
If the gas station clerk has to leave their place for any reason, then on the station, the vendor menus don't even pop up when they have their ID on.

**Comment by fluffe9911** [comment]
That's... a weird bug uhm don't have any idea how to fix this honestly although if its only for station vendors should not be that big of a problem since gas station clerks should not be on the station in the first place in most situations will ask around though to see if anyone has any idea how to fix this

edit fixed
