### ISSUE TITLE
Bring back [Ultra] Priority whitelisting for roles.

### ISSUE THREAD

**Issue by Lynameep** [yogstation13/Yogstation#4620]
Altoids said this wasn't in the rebase and I thought it'd be nice to bring it back so people who are able to do their job properly have the best chance of getting a role through whitelisting.

**Comment by ThatLing** [comment]
I personally hate this feature because it just makes it so people who familiar with a job get to play it every single round, leaving less experienced or newer players to play other jobs. Even if they are decent players that have already have experience with every department and want to learn more important jobs. -support

**Comment by Lynameep** [comment]
It was mainly for command roles only anyways.

**Comment by Altoids1** [comment]
> I personally hate this feature because it just makes it so people who familiar with a job get to play it every single round, leaving less experienced or newer players to play other jobs. Even if they are decent players that have already have experience with every department and want to learn more important jobs.

I can understand that, but I would still like to have something like this back for roles like Captain, HoS, & AI, since they are roles that really need their player to be at least mediocre in order to be functional and capable of operating without breaking Space Law or their AI Lawset. Letting randos operate these jobs during highpop isn't a terribly good idea.

If this took the form of something more probabilistic and weighted instead of real "whitelisting," then I would love to integrate this into critical jobs like those.

**Comment by Lynameep** [comment]
> If this took the form of something more probabilistic and weighted instead of real "whitelisting," then I would love to integrate this into critical jobs like those.

What if there was a limited number of times you could do this until you would need to wait before doing it again? One ultra priority every... three rounds? three every ten?
