### ISSUE TITLE
Character not fitting in cloner

### ISSUE THREAD

**Issue by The-Lieutenant** [yogstation13/yogstation#470]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
For some reason, my character wouldn't fit in the cloning scanner. I was playing as a preternis chaplain. At first, we thought it might be because I had a sword on my back, but even after pulling everything off my character, they still wouldn't go in the pod. An admin tried resurrecting me from the player menu, and apparently that wasn't working either.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by X-TheDark** [comment]
What exactly do you mean by not fitting?

Can they not close the cloning pod? Or does the scanner open/close when you click it while having the body grabbed (instead of you being placed in it)?

If it's the latter, it's the way the blasted thing works. You can't just click on it while grabbing a body or mousedrop the body onto the scanner...something that no doubt needs to be implemented.

**Comment by The-Lieutenant** [comment]
They could open and close the door, but not get me into it under any
conditions. Other bodies went in fine, just not mine.

**Comment by Cruix** [comment]
Closing this in 24 hours if no one can reproduce this or provide more information.
