### ISSUE TITLE
Make sus toolbox fit in backpack. Make combat gloves show up as black gloves on examine.

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#487]
As above.

Reasoning-nobody buys sus toolbox. Making it fit in backpacks means someone might buy it over just stuffing a box with tools from the autolathe.

Combat gloves offer very little for the instant-perma-on-sight they otherwise have.

**Comment by Super3222** [comment]
Sus toolboxes are more of a contingency weapon. Something that you don't buy straight ahead but, when you are in a sticky situation which you can't get out of and have extra tc? You buy it.

Which is why almost no one uses unless they HAVE to.

A good idea is making all of the tools colored red, and work as fast as cyborg tools. If not, almost as fast.

'You can see millions of tiny nanomachines within this tool working so incredibly fast, it's hard to pick them out from one another. In each gesture you make with this tool, they manage to work their way to producing it 3x over.'

As for combat gloves, meh. Whoever wants to take this, make sure you don't completely rename combat gloves black gloves. Make a subtype named black gloves, with a very apparent description that reads out "Syndicate" or "Traitor".

**Comment by X-TheDark** [comment]
There's absolutely zero reason to buy this beforehand and even with this "buff", it's going to be absolutely useless while you can stuff all of blue toolbox tools inside your survival box you start with.

**Comment by SeikoTheSeal** [comment]
You can't really be perma'd for having the toolbox. Its a fucking toolbox with a different paintjob.

**Comment by Cruix** [comment]
You can also find these on the derelict and lavaland. Granted, there is a lot of traitor gear you can find on lavaland, but with how mundane the toolbox is it really does not make sense to perma someone for having it. Having the toolbox fit in backpacks would be a useful buff even if everyone just empties it out immediately and puts the tools in a normal box.

**Comment by Super3222** [comment]
Still, I feel like some traitor gear are truly 'help me get out of this situation' ones which serve their purpose. Making them fit in backpacks is okay-ish

**Comment by X-TheDark** [comment]
Perhaps make this a one-time use implant that you can click action button to get the toolbox spawned anywhere. Now THAT would actually make it pretty damn good.
