### ISSUE TITLE
Plants need to provide Oxygen.

### ISSUE THREAD

**Issue by 13gome0220** [yogstation13/yogstation#535]
Plants should produce O2 to the atmosphere. It adds more purpose to "Life Bringers" in the Lava Lands. They could create a habitable environment in the Lava Lands by spreading plants across the map. This also helps with Life Bringers trying to breathe in the Lava Lands. They do not start with any Oxygen Tanks or Breath Masks. Please add this in.

**Comment by ParagonPrime** [comment]
They intentionally don't start with masks because everyone would beeline for the mining station.

Each faction has a certain gimmick that sort of prevents them from accessing the station too easily.

-Golems usually start far away, move slowly, and lack shelter capsules. They also have their own homebase and have little reason to go to the station.
-Ashwalkers are antags and valid to kill, and are generally very weak until they've killed a lot of mobs and have fancier armour
-Prisoners, seemingly without exception, spawn in really shitty places far from the mining base. To offset that, they get _really_ good gear (which is in very short supply)- the M1911 is pretty lethal and the SWAT helmet is downright the best armour in the game, iirc.

Also, keep in mind how particle physics work. Diffusion is your enemy here.

Spreading plants across the map would NOT fill the planet with oxygen and make it habitable any time soon.

On the other hand, I do agree that some plants should produce oxygen when properly watered and fed, draining CO2 from the air and adding O2.

**Comment by AdamElTablawy** [comment]
Grass tiles produce small amounts of o2 (not that it matters-on lavaland atmospheric changes are wiped away immediately because it's a giant ass planet and all the gas floods into the atmosphere)

Space tobacco, tea astra, and the ambrosias all have healing chems that will let them leave the vault and spray weed everywhere if they want to, so.
