### ISSUE TITLE
Unable to replace Fore Maintenance APC

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5881]
So I broke down the original that was damaged. I tried placing a new one in the same spot, in other spots, all throughout it and it kept telling me there was one even though I destroyed the one and the place had no power. I assume it's detecting the courtroom and fitness room APCs as being present but those do not affect this area.

Anyway to fix this or can we just do away with APCs in maintenance?

**Comment by Lostlarry** [comment]
have you tried placing it on the atmos closet wall? or the ones separating maint and fore hallway?
because those are only walls that actually belong to fore maint so the new APC has to bee built there
the roundstart ones are dirty cheaters

**Comment by MegaEmpirical** [comment]
This APC has nothing to do with the hallway  so placing it in the hall won't do anything. However, placing it in the sec atmos room might woke since it won't have any more APCs to detect but that room is still considered apart of that area, well done. Will have to test.

**Comment by Lostlarry** [comment]
the wall separating the hallway and fore maint 2(name of the area) still belongs to maint area so placing APC there should work

**Comment by MegaEmpirical** [comment]
I belive it will but I think we should really consider maybe moving away from APCs that are placed outside their rooms. They cause too many issues. I was a fan of the maintenance access for them, still am, but they're incredibly obnoxious.

**Comment by Lostlarry** [comment]
you could keep the APCs in maint just move the actual maint APC to spot where you could build it

**Comment by maxion12345** [comment]
tested this in a private server, it highly depends on what wall you attempt to place it on. Placing it on a wall inside the actual maint works 100% of the time, however, you cannot place it on the walls of EVA, the vacant commissary, lawyer's office, det's office, the garden, aux tool storage, the solars, and aux base construction.

The reason is that the walls are mapped to be considered as to be considered included with the entire office/area, so even though you are placing it from the outside, it's still considering it as "inside" and won't let you because that area already has its own APC. No real way to fix this outside of coding some weird shit that might let you chose what area an APC powers if you place it on a wall while standing in a maint area.

**Comment by patpol4** [comment]
The wrong interaction when placing an apc was fixed in https://github.com/yogstation13/Yogstation/pull/12947 .
As for placing it in random places, this is just how areas are mapped, usually it should work.
