### ISSUE TITLE
CMO and RD hardsuit

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#593]
CMO should not be actively getting bodies from space, that's the paramed's job, who should probably get the medical hardsuit over them.

RD doesn't need a hardsuit

they have access to the command EVA suits

stop powercreep 2016 heads are too op

**Comment by SeikoTheSeal** [comment]
Move CMO hardsuit to paramedics office. Remove RD's suit.

**Comment by ParagonPrime** [comment]
Eh.

The RD hardsuit is meant to be an enhanced bomb suit that can work in space.

I'd like for it to stick around just in case, since having the ability to dispose of bombs safely in depressurized environments is lovely, but maybe move it somewhere- the armory, for instance, or the Mass Driver room of toxins.

**Comment by ParagonPrime** [comment]
The Paramedic getting the CMO hardsuit is 10/10 though

**Comment by Robertruler77** [comment]
RD need the suit for toxins test retrival. Gotta go EVA otherwise, and thats unreliable. Maybe change RD hardsuit to a suit that can't leave toxins test?

**Comment by ParagonPrime** [comment]
sounds like a lotta snowflake coding for just about nothing

and what if there's a bomb elsewhere than toxins?

i mean there's really not much issue with the RD hardsuit- he has much more of a use for a hardsuit than the CMO, it's a super snowflake hardsuit that will instantly allow sec to know who just blew a hole in the armory

if you have an issue with it just nerf the non-bomb resistances a bit
