### ISSUE TITLE
Donator Antag Tokens: a formal system

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#597]
Please don't give me the "b-but we don't give antag tokens, reee" spiel. Yogs is dying and I'm pretty sure that this will be part of what we need to save it.

That said, I hope the system I have planned out is simple but fair:

**The Token Mechanic**
Once a week, starting on the day of their donation and refreshing exactly one week thereafter for the length of donation time, donators are given _one_ antag token, shown on their game preferences panel.

This token does _not_ carry over to the next week, so no stacking tokens; one guaranteed antag round _per week_. This number can potentially be increased for higher levels of donation to encourage more cash cash cash.

Upon clicking the button that says "you have an unredeemed antag token!" (_which can only be done before a round starts_), you're given a drop-down menu of antag choices.

Clicking one will _automatically change the roundtype to accomodate it_ (if it's a mode-specific antag; so if it was going to be a regular traitor round and someone selects Ninja, the roundtype doesn't change but ninja will be spawned at the start).

**If the antag is a singular one, such as wizard, blob, ninja, revenant, etc., redemption is on a first-come-first-serve basis; attempting to select an option after someone else will deny you.**

**If you select a group antag, others selecting the same antag will be added to your roundstart team, again on a first-come-first-serve basis, so if the server populatoon-controlled slots fill up, you can't redeem.**

Additionally, to make things easy on admins planning events, they can _manually disable token redemption for one round_. This automatically turns off on server restart so that klutzy admins forgetting to re-enable it don't make a sad for donators.

**Comment by X-TheDark** [comment]
Generally, communities (which I assume regular Yogs players are) aren't saved/formed by enticing donations. 

They are saved/formed by making it enjoyable for players to play on the server and guaranteed donor rounds sounds like (again, my opinion) one of the worst things one can do at this point.

I'd love to offer something else, but unfortunately, I don't have any ideas on how to make our server more enjoyable **for everyone** rather than a **select group of players**.

**Comment by ShadowDeath6** [comment]
>changing the roundtype to let one donator be blob

:laughing: 

best thing ya can do is to add them to the antag list for that round if they have their prefs on, it's probably possible by setting their antag weight to some obscene number

**Comment by ParagonPrime** [comment]
then disable ninja/blob for certain roundtypes

i guarantee you most people will spend their tokens on ninja considering it's practically the holy grail of antag rarity, so stopping that is a bad idea

**Comment by ShadowDeath6** [comment]
people like playing ninja because it's fucking op, giving people a free ninja tier midround antag is dumb and will be abused so fucking hard

**Comment by GrayRachnid** [comment]
>yogs is dying

Yeah no

**Comment by ShadowDeath6** [comment]
>implying yogs hasn't already died from low blood sugar due to sodium haha quality joke 2016 :joy:

**Comment by ParagonPrime** [comment]
Helpful as always, Gray :^>

**Comment by X-TheDark** [comment]
Just so we are on the same page, I hope that by "Yogs is dying" you meant the current problems with hosting, rather than the community, because if it's the latter, I strongly disagree, we are rather consistent in our playercount.

Also, I don't mind this idea **only because the server is having monetary problems right now**. If that wasn't the case, I'd go on a huge rant about community being fostered by making it fun for **everyone** rather than **those who pay**.

**Comment by ParagonPrime** [comment]
Yeah, I meant the monetary problems bit.

Honestly I wouldn't be _hugely_ against this even normally, but I'm proposing it as an emergency feature we can shut down once it serves its purpose.

**Comment by Alek2ander** [comment]
>yogs is dying

>add literal pay to win

Right.

**Comment by ParagonPrime** [comment]
>mfw people don't even read

how is this pay to win

you get ONE guaranteed antag round, ONE, out of an entire week of rounds where plenty of non-donators will have plenty of tume to get antag

this token does not in any way, shape, or form guarantee you a win. if you're an unrobust little shit and you choose ninja and you get fucked, that's on your head- it's just letting you learn from it and get ninja again within the next century or so

**Comment by ShadowDeath6** [comment]
no midround antags

no solo antags

no changing the round to suit your antag choice

is fix

**Comment by Super3222** [comment]
but hey, if September 27 turns out to be doomsday you can rub it in peoples faces

**Comment by Alek2ander** [comment]
nonantags don't get greentext
antags can get greentext
greentext is win
you pay for greentext

**Comment by Super3222** [comment]
> nonantags don't get greentext
> antags can get greentext
> greentext is win
> you pay for greentext

You just reminded me of civilian objectives.

**Comment by AdamElTablawy** [comment]
look i mean yogs IS dying due to lack of donator funds temporarily and this will encourage people to donate

but  this is also 'pay to win.' which is bad.

honestly i'd sooner fix antag weight and have donors always start at 150 antag weight or higher so that they have a higher chance of rolling antag but even that sounds cancer as hell

**Comment by ParagonPrime** [comment]
seriously how is this pay to win???

pay to PLAY, if you really wanna get technical

**Comment by tromacodes** [comment]
Donors only and should ever get cosmetic level items for donating.  Donations should be based on running a good server not bribing people to donate.
 Also I see problems with people who are just donating for rewards and not because they believe we are a good server that deserves donations.

**Comment by ParagonPrime** [comment]
Do you give a shit why people donate, or what for, so long as they do it and you can continue to play your spessmens on a server you like?

This isn't about personal ethics or "b-b-b-but it's UNFAIR!!!". It's about making sure the server can fucking keep running.

**Comment by tromacodes** [comment]
Yes I do.  If the reason why they aren't donating like they have in the past is because the quality of the game environment has decreased then fixing it through bribery isn't fixing anything at all and contributes to a ever increasing toxic environment that people don't want to fund. 

 Also  ethics are important.

**Comment by ParagonPrime** [comment]
Not... really.

I don't think we were getting particularly many donations before, either. Just that Hardy could actually afford to fund the server.

He's currently in a hard spot finanically and can't fund the server himself, so we're _relying completely_ on donators right now.

**Comment by Alek2ander** [comment]
Add a fucking progress bar for donations. And if the goal isn't met, shut down, and post a huge announcement. Either people rush to donate to get it working again, and that's good, or the community is dead, and doesn't deserve a server.

**Comment by ParagonPrime** [comment]
Looks like we've got an extra three months so this isn't immediately pressing, but I'd suggest we still have this coded on backburner as a side project and can switch it on if we need it.

**Comment by Kmc2000** [comment]
>change the rountype to accomodate that

😂🔫

**Comment by Super3222** [comment]
> civilian objectives.
