### ISSUE TITLE
Allow pre-defined character name in case of non-antag role which will be randomized in case of antag role

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#626]
Currently there are only 2 options: pre-defined character name and randomized name.
I would like to see ability to use pre-defined character name in case if you start as non-antag, but if you start as antag, you will get randomized name.

**Comment by Groxic** [comment]
Or a predefined antag name?

**Comment by ParagonPrime** [comment]
Predefined antag name is possibly the worst idea ever.

It would be sticking a HUGE piece of metagame-bait right in front of everyone for... no discernible reason.

I have no problem with features that can be meta'd so long as they _actually have a purpose_

**Comment by Paragonid** [comment]
Purpose is subjective...
The idea behind my suggestion is that it's preferable to have a known name e.g. when you play in security. People will know what kind of security you are, that you are consistent, competent and able to teamwork. But if you usually play as security with that name and then suddenly get another profession, your name will give away you as antag.

**Comment by ParagonPrime** [comment]
I'm not talking about your idea; I'm saying that having a name that only shows up when you get antag is a stupidly bad idea and I hope it's obvious why.

**Comment by Axemeaquestion** [comment]
Paragon, its a RANDOM name when antag. Not pre-defined. It's in no way meta-bait, and it actually cuts down on meta-bait because you can't identify antags by breaks in their normal shift patterns, e.g. you notice a chef who's normally in the kitchen 24/7 making food scoping out sec and following you, you know there's something off: this is alleviated if they have a random name.

**Comment by vladlds** [comment]
@Cruix why are we Controversial on this?

**Comment by Cruix** [comment]
Because there are some people who think this is a bad idea and some people who think this is a good idea.

**Comment by ParagonPrime** [comment]
@Axemeaquestion - my comment was in response to somebody who now deleted theirs, probably out of shame for how cancerous an idea that was.

The idea of an entirely random name is fine.

**Comment by tromacodes** [comment]
This is inappropriate for the theme of the game. The whole idea is that anyone could be a traitor at any given round regardless of whether or not you see them every round. This would reduce the need for vigilance.

**Comment by vladlds** [comment]
@tromacodes, you seem to discuss some different issue(s).
1. A lot of people play with one nickname, including admins. And game directly supports this.
2. A lot of people play one profession round after round. And game directly supports this.
3. A lot of people metagame / powergame out of known character names: some don't recruit for rev/gang if they don't know your name, some will work together/help out much sooner if they know your name and there are much more for it. And due to 1 and 2, game directly supports this.
4. Normally spawned security and captain can not be traitors. And game directly supports this.

You can try to address those, if you dare, but this suggestion is just a consequence and quality of life for the current system.
