### ISSUE TITLE
buffing holoparasites

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#640]
if someone has a holo in them the holo should take the damage from the explosion, not the person

the idea that someone takes double damage from an explosion is fuckin dumb and it makes things like the protector holo hyper garbage since the person still takes however much damage gibbing does from a shitty ass minibomb when they have a holo that takes .04 times damage from all sources of damage

**Comment by Paroclomas** [comment]
I thought holoparasites were op already, at least i wrekt some serious havoc on the station using standard parasite

**Comment by AdamElTablawy** [comment]
there's no need to buff holoparasites since our players can't kill the easiest traitor item to defeat

they aren't op but most people don't understand harmbaton+ drag or that holoparasites are too weak to kill you before you can kill the host unless you're stunned

anyway protector holo taking dmg from explosion would be okay, i guess but i don't think gibbing does damage, it just deletes and spawns gibs

**Comment by Super3222** [comment]
> holos needing a buff, ever.

They don't need a buff.
And if they take double damage from explosions, that's good. This'll enable people to play it smart and not turn a blind eye after letting their holo go on a mindless rampage.

And if a bomb's going off, a holo logically wouldn't want to be anywhere near it, Shadow. Don't they still have the ability to instantly teleport to their caster... That's their fault otherwise. The least that could happen would be jobbans for shitty holo's (if there isn't already), that'd be a better solution.

Lastly, from my understanding that's not how stands even work. They come out, and that's when they can protect their caster. Nothing happens while they're inside aside from telepathy.

**Comment by ShadowDeath6** [comment]
if a bomb's going off the holo would ALWAYS be near it due to it requiring them to be LoS to their caster

**Comment by Paroclomas** [comment]
But if they are inside the host and the bomb goes off does it harm them too?

**Comment by ShadowDeath6** [comment]
no, but the host will probably still die due to it being a bomb

**Comment by Paroclomas** [comment]
so the problem is that holoparasites don't protect you against bombs? they are still plenty useful in many other situations. Specially taking into acount what adam said about most people not knowing how to deal with antags.

**Comment by ShadowDeath6** [comment]
the problem is that bombs are a counter to every antag, even traitors that waste the tc on buying a bomb resistant holo

**Comment by Paroclomas** [comment]
maybe the issue would be to nerf bombs somehow?make them more expensive and harder to get out of toxins?

I personally like the idea of huge bombs being avaivable, but if its too unbalancing maybe it should be reviewed.

**Comment by Super3222** [comment]
issue won't be fixed by nerfing bombs. that's a bad way to go.

just make protector halo bomb resistant, shadow. or make bombs do tickle damage to the holo & only the holo. if a the user gets hit by a bomb, that's their own fault.

**Comment by X-TheDark** [comment]
The whole shtick of holoparasites is that they are, effectively, immortal and transfer all their damage to the host.

I'd be fine with making holos (all of them) bomb immune, though.
