### ISSUE TITLE
Gravity room is not wired to power grid

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6531]
Is this intended? It's not connected at all to the station's power by default.

**Comment by FlamePrince** [comment]
It's become part of my standard SOPs to wire the gravity generator into the grid after I'm done with the engine - it is possible that this may have been intentional in order to prevent a powersink from draining the generator and causing a shutdown. It's definitely ideal to charge the SMES then disconnect it from the grid so that this cannot happen.

**Comment by MegaEmpirical** [comment]
Yeah, I'm really not sure. It could easily be an oversight though. Comparing previous versions and other maps will be useful.

**Comment by patpol4** [comment]
This has been fixed
