### ISSUE TITLE
Emags no longer let you get things from vending machines

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6598]
Used to be that it removed restrictions/costs but now it shorts it (as far as I can tell this does nothing at all) out and it doesn't change its behavior at all.

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/2649 Changed it last, it never removed costs (since the emag check for vending was removed in the economy PR), but it did use to remove access requirements. I'm not entirely sure it's a bug, but given that it's goof I wouldn't be surprised if it is.

As for what the emag currently does, it just removes access restrictions on putting items inside of the vending machine :)

**Comment by MegaEmpirical** [comment]
Hmmm, then I'd think it should be retooled? Or maybe retool agent ID to do something with economy?

But the putting stuff in thing is kind of interesting

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
