### ISSUE TITLE
Implanted people can be traitored

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation#704]
Basically what it says. If a person is implanted they can be traitored by an admin's CREATE ANTAGONIST button. Not via TP or something like that. But via create antagonist and if that ain't bullshit I don't know what is.

**Comment by ShadowDeath6** [comment]
traitors can be loyalty implanted

**Comment by Groxic** [comment]
I don't think things are loyalty implants anymore, but rather they prevent "brainwashing".

**Comment by GrayRachnid** [comment]
Traitors can be implanted, but they can't start implanted. Big difference.
This should be fixed.

**Comment by ParagonPrime** [comment]
It's a mindshield implant, AKA you can't brainwash the person. Loyalty to NanoTrasen not guaranteed.

That said, traitors should just completely reject mindshield implants because their own sleeper agent implant counteracts it. Much more balanced than traitorsec (AKA, give the traitor a bunch of armour, free long-range stun and detainment tools, and a perfect alibi to drag someone away and beat them to death in maint)
