### ISSUE TITLE
Slime blueprints count for the steal the station blueprints objective.

### ISSUE THREAD

**Issue by Silk-Touch** [yogstation13/yogstation#726]
Bug Or feature?

**Comment by timkoster1** [comment]
Most certainly a bug.

**Comment by X-TheDark** [comment]
Players decide, I guess...I'd be willing to call this a feature.

**Comment by Super3222** [comment]
This is a bug. It's just an error caused by slime blueprints being apart of the parent type.

Slime CE boots?
Slime Plasmatank?
Slime HoS Gun?
Slime Captain Gun?
Slime Hypospray?
Slime Teleportation Armor?
Slime Functionng AI?
Slime Nukedisk?
Slime Captain jetpack?

This is anything but a feature, and there should never be a steal objective that a normal security shouldn't have the authority to take away & brig you for (exception being the silly ones, like corgi meat or plasmatank)?

**Comment by ShadowDeath6** [comment]
I think this'd be a feature considering you can just take a picture to get the blueprint steal objective anyway. There are a lot of trivial steal items, at least you've gotta work for this one, instead of steal plasma tank / steal slime extract.

**Comment by Super3222** [comment]
> can just take a picture to get the blueprint steal objective

That's a good thing because it's still STEALING THE BLUEPRINTS. If red army and blue army are at war. Red Spy takes picture of Blue Army's war plans, THEY'RE GUNNA GET ARRESTED. And if they don't, blame the airhead officers.

Slime blueprints on the other hand are just a way to get slime's and monky's picked up and dropped off in more rooms than just the xenobiology one.
