### ISSUE TITLE
"Not" tick box for nanites.

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#7350]
Would be great if there was a way to sense if people weren't dead, or to basically reverse a sensor really easily. Examples being: Not being dead, not saying something, not in critical health, stuff like that. In regards to the death sensor, it would make setting up a defib nanite alot easier, and in regards to the not saying something. It would be pretty funny if you made it so people had to include "HONK" or something in every sentence, lest they get shocked or something.

**Comment by CMOisLing** [comment]
A “not” version of every sensor but voice wouldn’t work. And voice sensors pick up everything spoken by everyone in bearable range. So something like you are describing would be nearly impossible to work consistently.

**Comment by Saratoubi** [comment]
A not version wouldn't work? Like code wise? Cause a sensor that checks if someone is "not" dead would be nice. And another one that would be nice would be a "not" race sensor. Course thats kinda redundant, but it could work. And as for health sensors a not sensor would basically just be flipping it from above to below and what not.

**Comment by CMOisLing** [comment]
> And another one that would be nice would be a "not" race sensor.

That already exists, race sensors have a "is not" mode


> A not version wouldn't work? Like code wise?

Codes are not off/on signals they are done in pulses. A sensor is triggered when a condition is met and it sends out a pulse on whatever code it is set to, and triggers other programs. A death sensor sends out a pulse when you die, it doesn't stay on while you are dead, same with health sensors. Thats why race sensors are required to be triggered, because they don't output a constant signal.

I'm not sure what exactly you are trying to do but if you want try this setup.

Death Sensor
   "Sent code" = 1

Critical Health Sensor
   "Sent code" = 2

Health Sensor  // Just in case they are revived from above 0 health
   "Health Percent" = 90
   "Direction" = Above
   "Sent code" = 2

Signal Repeater
   "Activation Code" = 2
   "Deactivation Code" = 1
   "Trigger Code" = 3
   "Sent Code" = 4



This should allow you to check whenever someone isn't dead, Pulse code 3 and if it doesn't reply with code 4 then they are DEAD. You can setup a timer to pulse it every second if you need to.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
