### ISSUE TITLE
Positron flavor text should be changed

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7354]
![image](https://user-images.githubusercontent.com/36208065/71110561-8a28e100-2195-11ea-9535-2402aaa88f51.png)

It says that above all, you should do no harm but this seems pretty counter to how borgs will often work and so it should be removed. Since borgs will often get subverted or have laws that will permit harm.

**Comment by SomeguyManperson** [comment]
borg laws override the posibrain greet text since laws > everything else, this only really stops posibrain mechs from going on a rampage or being used by traitors

**Comment by Hopekz** [comment]
Psibrains don't have laws at all because they're not technically "silicons".
This flavortext at the moment is the only thing that Psibrains need to obey because they can't even see laws if they wanted to.

I do agree that maybe the Psibrain flavortext might need to be changed from an Asmov type command to a more general "crew" wording otherwise something needs to stay in to prevent people from going on killing rampages in lawless psibrains.

**Comment by Ratvar** [comment]
I propose a fix to this problem once and for all: give posibrain asimov lawset by standart.

**Comment by Hopekz** [comment]
> I propose a fix to this problem once and for all: 

I agree

> give posibrain asimov lawset by standart.

I disagree with this approach. 
If anything I'd like for psibrain mechs to be linked to an AI similar to how borg shells are linked. 
This would also make it so that mechs can have different lawsets and give more tools for silicons to work with in their quest for world domination or being helpful to crew when they're not subverted.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
