### ISSUE TITLE
holoparasite memes

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#742]
https://github.com/yogstation13/yogstation/issues/640

going to be adding the lightning stand disarm the person it hits because it effectively "stuns" you. Also discourages the meme of only using standard / chaos holo

making all holoparasites take the damage for their hosts from bombs while they're inside their hosts, this will only really affect bomb and protector holo since they have the only noticeable bomb resistance (keep in mind this is only when the holo is inside the host)

other balance memes (this is where you talk about said balance memes)

I might add some rng factor stats with an average a bit lower than current ones, just to add some variation between standos

I like this feature pls no bulli

**Comment by Super3222** [comment]
> because it effectively "stuns" you.

but why? what counter would there be? It'd basically be like having an alien hunter crawling in and out of your body, jumping out, disarm spamming somebody, dragging them back to you, and waiting for the next move.

The only way to really balance that out is either to make it unable to stun someone already stunned or make it move slow. Because people NEED to be able to run away from holoparsites.

**Comment by ShadowDeath6** [comment]
it wouldn't be able to stun people, I was just using that statement as reasoning for it being able to disarm someone. Lightning suffers the most from people running away, which is intentional. Making it disarm(not stun) would actually make it more fearsome in close quarters.

**Comment by Super3222** [comment]
Eh, thought you were adding it in. I really need a crash course on holoparasites and quite possible the animeme they come from

**Comment by ShadowDeath6** [comment]
muda
