### ISSUE TITLE
Minsky station Viro not stocked with materials to start a virus.

### ISSUE THREAD

**Issue by Rdrazga** [yogstation13/Yogstation#7444]
## Round ID:
27008

## Reproduction:
Minsky station Virology not stocked with materials to start a virus, This includes not having a starter rhino or flu virus, No synaptazine, no unstable mutagen, ect. The latter items can be easily made but the lack of a rhino or flu virus makes starting virology impossible without a random event or a large amount of miasma in the air.

**Comment by Hopekz** [comment]
There seems to be multiple unfinished departments in Minsky 1.0 .
Hopefully 2.0 will address these issues otherwise I see Minsky 1.0 being taken out of rotation because of its sheer size + those "unfinished" issues. Good luck even finding a fire extinguisher on the walls near escape when its needed.

**Comment by Ktlwjec** [comment]
Yeah minsky isn't meant to be used so I'm not going to bother with this, someone else can

**Comment by Ktlwjec1** [comment]
Closing as this map is removed.
