### ISSUE TITLE
Printing security records and posters

### ISSUE THREAD

**Issue by Oakboscage** [yogstation13/yogstation#754]
The option to print security records and wanted posters from security record consoles exists but is barely used since there's little benefit to do so. I propose that the system is changed so that records and posters that are printed out to all consoles or there is the option to do so. That way posters would actually be put into circulation and records would be available to read at the offices.

Hopefully this would increase use of this otherwise overlooked feature.

**Comment by Cruix** [comment]
I think this would just lead to enormous amounts of posters and records lying on top of the computers in most of the departmental security posts.

**Comment by Super3222** [comment]
There should be a public criminal record / bounty list that any crewmember w/ a pda can access.
And an option in security consoles, requiring officer attention, that lets them toggle between showing records to that log or not.

Oak's proposal is also pretty good, because think about it. The Warden clocks in, gets info on some sorta criminal, sets up crimes, prints record, hits "print to all computers", than all the other officers at their checkpoints via cargo, science, engineering, and medbay will get it and hang it up around their divisions.

With that, posters will be going up in more places than just the sec hallway, which gives posters the exposure that they need.

**Comment by puremanbird** [comment]
This is a good idea. Wanted posters help inform the crew that have trouble doing their job and focusing on radio chatter.

**Comment by Kmc2000** [comment]
>bounty meme


You mean the newscasters?

Yep nobody uses em, but they're surprisingly robust
