### ISSUE TITLE
Suggestions on maintainability

### ISSUE THREAD

**Issue by Bawhoppen** [yogstation13/yogstation#76]
As far as I am aware, one of the goals with the rebase was to only keep some of the most key features, so you can stay up to date with the tg master branch more easily.

Keeping unique features and doing this is still somewhat of a problem though, so my suggestion to you guys is, that if its a small noncontroversial feature (as an example those wanted posters), or its a new item, you should PR it to the tg main branch, and if it's an item, we can just keep it in the code on tg, then you can just add where it spawns (or uplink or whatever) on your fork, to allow stuff to be much more easily updated.

On tg we just started using a system of needing to fix bugs to get mergetokens for your PRs to be eligible to be merged, but I have convinced some of our maintainers if its for your guy's rebase effort to let it slide.

**Comment by X-TheDark** [comment]
As appreciated as this suggestion is, I see no reason to clutter /tg/ code with our stuff that they won't use.

**Comment by X-TheDark** [comment]
Keeping the new features/items is not difficult. It's when our codebases differ on the same issue (Shadowlings, for example, different values, different methods of approaching the gamemode) that causes the most problems with keeping us up to date.

So, while your suggestion is very welcome and I thank you for battling the maintainers for the whole PR without Fix PR thing, I don't think there's much point in PR'ing our items that will never be used on /tg/ and ultimately, are not the cause of the difficulty of keeping up-to-date with /tg/.

The biggest causes of problems are:
* Differing values/methods on the same thing;
* Map;

That's really it, in my opinion.

**Comment by Bawhoppen** [comment]
Well, I'm not referring to just items, for example your cortical borers and such could be added to the main branch and kept in the code, and items in the code can still be used as loot for maps, admin events, etc.
Some of the most absolute small things it's probably not worth bothering but, it could be beneficial for some other things.

**Comment by oisin100** [comment]
Our plans aren''t to keep up to date with /TG/ all the time, that would make it terrible to update.

We're updating to /TG/ once to take advantage of what /TG/ have done with the Goon leak and 510.

Maybe in a year or so we could do another rebase, but for now updating to /TG/ constantly will be a pain.

It used to be possible because we had a small development team meaning we didn't have many unique features, but now we have so many that its just conflicts everywhere.

On the idea of pushing all our features to /TG/, I want to keep our features unique, if you want them your gonna have to port them yourselves.

**Comment by AdamElTablawy** [comment]
@Oisin100 that's stupid and you're being stupid if you want 'muh snowflaek uniques'

1. It helps /tg/ with all the things that could be adminspawned or floating around in code for their own development

2. It helps us because we should be keeping up to date with /tg/. Not keeping up to date with them got us in this mess. They're bigger and better than us so we should rebase and update as often as possible.
