### ISSUE TITLE
Odysseus strafing mode doesn't work

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#795]
Odysseus mech has strafing mode but nothing changes when it's turned on, it just turns.

**Comment by X-TheDark** [comment]
Strafing mode on Odysseus doesn't actually make him strafe, it instead makes it so you turn AND move at the same time, instead of (taking Ripley, for example), having to turn, having a delay and then moving.

**Comment by 00aquir** [comment]
It behaved the same way I guess, saw no difference...

**Comment by X-TheDark** [comment]
The difference is not as noticeable, because Odysseus is pretty fast.
To verify this, press the direction opposite of where Odysseus is facing:
* If you do this without Strafing, the Odysseus will just turn, but not move (and you'll need to wait (a little bit, due to his speed) to move again);
* If you do this with Strafing, the Odysseus will turn AND move at the same time;

**Comment by 00aquir** [comment]
Maybe I didn't notice because I turned on to see the strafing.. oh well.

**Comment by X-TheDark** [comment]
But yes, it deliberately doesn't work for Odysseus the same way it works for Ripley (the code is purposefully different). Not sure if it should be changed to be consistent across all mechs.
