### ISSUE TITLE
Accents Persist Between Characters

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#7991]
Issue reported from  Round ID: 28274 (Yogstation 13)

Reporting client version: 512.1488

When changing from one character to another, accents remain the same in the character settings menu. They do not save with the current character set up.

**Comment by Hopekz** [comment]
Feature!
![635161772642271233](https://user-images.githubusercontent.com/24533979/77221617-2e198400-6b19-11ea-8bd9-7c4ec03ea11c.png)

In all seriousness, this was probably done so that the AI and Cyborg can have accents as well if they're bound to your character then they wouldn't apply to them I think.
