### ISSUE TITLE
Debug Chem Synthesizer unit input button unresponsive

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#8373]
obj/machinery/chem_dispenser/chem_synthesizer

The input button to adjust chemical amounts using the debug chem synthesizer no longer works.

The pop up to adjust the unit amount (1u-300u)no longer appears when selected after creating a beaker and inputting a chemical.

As of now only 10u can be dispensed at a time.

**Comment by Rayisken** [comment]
![Debugsynthesizer](https://user-images.githubusercontent.com/38535833/80866068-c481af00-8c5a-11ea-9229-2bb1e02f7dc8.gif)

**Comment by Partheo** [comment]
![image](https://user-images.githubusercontent.com/10659549/86493379-541d0a00-bd3f-11ea-8c45-2d070e5229e2.png)

This has been fixed by one of these commits: https://github.com/yogstation13/Yogstation/commits/5e514f81e7bb851897af799ff2b994e14c7e9799/code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
