### ISSUE TITLE
Gem-encrusted hardsuit helmet doesn't count as a wizard hat, so spells that require one won't work

### ISSUE THREAD

**Issue by Leatherturtle** [yogstation13/Yogstation#8477]
:( very sad that I had to be the one to suffer and report this in my wizard round
## Reproduction:

 This can be reproduced by being a wizard, buying the gem encrusted hardsuit, and spells that require a wizard robe, then attempting to use them, you will quickly discover you cannot use the spells if you do not have the wizard hat on, but you do have the hardsuit helmet on WHILE BEATING BEATEN TO DEATH.

**Comment by Smudged** [comment]
Yeah, I actually experienced this on the same day you did a couple hours before, 
The wiki doesn't have information on it or a bold warning, since this did cost my own round too. In the wizard menu it does say it counts as a  wizard robe, but no where in the description does it say that the *HOOD* doesn't count as a wizard hat or why it shouldn't work.

**Comment by SomeguyManperson** [comment]
fixed by #8478
