### ISSUE TITLE
repost of my old species rework thing X-The-Dark please add this to projects

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#850]
null

**Comment by puremanbird** [comment]
I like this. I like adding more complexity to the game.

**Comment by Super3222** [comment]
YogMed best med.

**Comment by Ephemeralis** [comment]
Let's not make Preternis into IPCs, please. Remember that races should provide mild alternate differences in gameplay, not a WHOLLY different experience from playing the game otherwise.

Draining APCs is an interesting mechanic and probably something we should look into. 

The chemical metabolism thing is very interesting and we should definitely do that.

Rad and clone damage immunity is a flat no. That's too huge a bonus. Same deal with flash weakening.

Virus immunity but acting as a carrier is a novel mechanic and probably also something we should do.

Teslium interaction is pretty unique, and seems good to add.

**Comment by darkwahn** [comment]
Why would partly metal people be weaker to brute?

**Comment by AdamElTablawy** [comment]
@Ephermalis

We're not doing this your way. Your way was lame.

Species are now going to be heavily different, not just stylistic changes with light stat boosts. You can talk about species being minor alterations all you want, but the fact remains-it's not happening.

This issue is the only time i'll ever outright say to anyone-my way or the highway.
