### ISSUE TITLE
Revamping Secborgs

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#924]
W.I.P.

**Comment by Time-Green** [comment]
Best issue :+1:

**Comment by AdamElTablawy** [comment]
secborgs are fine after they can no longer disabler spam, just ban shitter borgs like we do shitter sec

if they start arresting and refusing to release humans because TRESSPASSING they get banned (unless on V.A.L.I.D.H.U.N.T)

if they start arresting and refusing to release lizards, good, because FUCK LIZARDS

**Comment by Super3222** [comment]
One of the problems is the misinterpretation. They shouldn't have sec weapons / tools to begin with. That sort of authentic theme makes them feel like actual security officers thus leading them to actually catch criminals.

I feel like revamping (the majority) of their weapons to considerable alternates & then giving them fancy new sprites would be great. I already have the ideas mapped out. I just need to get around coding them.

**Comment by ParagonPrime** [comment]
ehhhhhhhh

currently the issue with secborgs it that they're extremely powerful and any faction fighting over the station that has command of the secborgs is incredibly powerful

so why don't we force all secborgs to have an alternate lawset that can't be changed by normal means? (so the only way to modify them would be via emag, clock cult conversion, etc.)

roughly, the lawset, named "PROT-3CTR", would be:

1. Do not use lethal force at any time
2. Ensure the safety of all crew members at all times
3. Attempt to separate conflicting factions from each other without adding further conflict
4. Prevent harm to yourself
5. Preside as a neutral authority to maintain peace

the reason i'm saying "station crew" is because nukeops are pretty fucking well balanced against secborgs, especially if we implement that thing adam wanted to do about slowing them down with damage

maybe we could also remove the stunbaton and let them have disabler only, but infinite disabler

and maybe a riot shield too, that would slow them down heavily and drain a lot of energy on being hit (then again that might be better for peacekeeper borg....)

**Comment by Super3222** [comment]
We are never adding back an infinite disabler. The idea is just too overpowered and by even suggesting that you've contradicted your earlier statement.

> secborgs it that they're extremely powerful

Infinite disablers are out of the question. Of all things given, Security borgs do not need riot shields. Borgs do not need shields, they are practically shields themselves. They can take lots of blows, and move at top speed.

For this idea, I WAS initially thinking of programming the revamped versions with their default law set. I like your rough idea for the lawset so it might still happen.

You set up a guy like a security officer, he's bound to act like a security officer. My idea is to change the model into something that is equal (or maybe a minor fraction less) to the strength of a secborg, but just in another whole fashion.

**Comment by Time-Green** [comment]
Actually, the Vtol upgrade does exactly that, it gives you infinite disabler, and hell is it OP

**Comment by ShadowDeath6** [comment]
>traitor sci uploads onehuman freeform
immediately lynched by secborgs because he's endangering the station

x d

**Comment by Super3222** [comment]
custom pre-loaded lawset (by and from) the start of the round. not a permanent one idiot

**Comment by ShadowDeath6** [comment]
>so why don't we force all secborgs to have an alternate lawset that can't be changed by normal means? (so the only way to modify them would be via emag, clock cult conversion, etc.)

**Comment by Super3222** [comment]
Yeah, no. I liked his LAWSET idea, but anything as permanent is bad. Let's get that clear.
