### ISSUE TITLE
You cannot drag objects out of the way on resin floor

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9329]
- it is empty floor, but you cannot drag things out of the way on it.

**Comment by ToGWtF** [comment]
Are you referring to xeno-weeds, and how you can click on a tile while dragging something to move it to that tile?

If so, that's because they aren't considered floor. Its an object on the floor and its blocking the floor tile so you cant click it. Alt+click the tile you want to move something on, and in the top-right it will show a list of all objects on that space and click the floor tile there and it will work.

**Comment by 00aquir** [comment]
you can pull and drag around objects on it the same way as on other floor coverings, doesn't matter if it's bare plating, reinforced floor, or covered wit h grass, etc. and you cannot reveal the floor under the resin if you are blocked by an object that you want to drag out of the way, I don't think you can see the floor under it at all, actually. it really should work without alt-clicks.

**Comment by 00aquir** [comment]
you can pull and drag around objects on it the same way as on other floor coverings, doesn't matter if it's bare plating, reinforced floor, or covered with grass, etc. BUT you cannot reveal the floor under the resin if you are blocked by an object that you want to drag out of the way, and I don't think you can check the floor under it at all, actually.
