### ISSUE TITLE
Proposed craftable item idea (with pictures!) - Makeshift taser

### ISSUE THREAD

**Issue by Yewmi** [yogstation13/yogstation#936]
# BEFORE YOU GET OUT YOUR TORCHES AND PITCHFORKS HEAR ME OUT:

I have had this idea for a while now, and even prepared some sprites for the item.
### Item name: _'E-Derr'_ (short for 'energy derringer')

![image](https://cloud.githubusercontent.com/assets/22177874/19024121/60818434-88c2-11e6-9949-0524bbbe3586.png) 
_You're basically fucked if you get caught by Sec with one of these_
![image](https://cloud.githubusercontent.com/assets/22177874/19024131/91bf63e0-88c2-11e6-8f00-6112ce25459f.png) Open ederr with no battery
![image](https://cloud.githubusercontent.com/assets/22177874/19024136/a229cc98-88c2-11e6-8a2a-441599960f46.png)Open ederr _with_ battery ("You struggle to stuff the battery into the slot, circuits and all.")

I like the concept of a makeshift, messy energy gun and went from there. This very, VERY tiny energy gun functions as an unstable, homemade taser.
## RECIPE:
- 1 igniter ![igniter](https://cloud.githubusercontent.com/assets/22177874/19024518/eeb0003e-88ca-11e6-9a51-012281b01e8a.png)
- 10 cable wires  ![cablecoils](https://cloud.githubusercontent.com/assets/22177874/19024522/f73e9954-88ca-11e6-976a-201b3fbc400f.png)
- <strike>1 homemade firing pin (crafted from a metal rod, requires a welding tool to craft)</strike> ![makeshift_firing_pin](https://cloud.githubusercontent.com/assets/22177874/19024608/5c35ba76-88cc-11e6-940b-94802bab6ca9.png)
  **the above idea was dumb in hindsight**
  **EDIT:** Thanks to @Super3222 pitching in some great ideas in the comments I've thought about one of the ideas he gave: Perhaps this gun has a 40% chance to **ignite the user** every time it fires, due to how unbelievably shitty the design of the gun is.
- 2 metal sheets ![metal-sheet](https://cloud.githubusercontent.com/assets/22177874/19024636/169abcd6-88cd-11e6-97a3-f31f67c7459e.png)
- 1 light bulb ![light-bulb](https://cloud.githubusercontent.com/assets/22177874/19024637/1c23eff6-88cd-11e6-9ee9-16fcd793de34.png)
- 1 glass sheet ![glass-sheet](https://cloud.githubusercontent.com/assets/22177874/19024607/503d2740-88cc-11e6-81ab-40cc47f7ad20.png) (gun has a light on it that changes colors to indicate its state)

_Tools required: Screwdriver, welding tool, wirecutters, wrench_
## STATS:
- Fires **disabler** shots, and **disabler** shots only.
- Needs to have an energy cell put into it before it can be used (opened/closed by activating it in hand)
- Has 1 shot per tier of energy cell (standard cell = 1 shot, high cap. cell = 2 shots, etc)
- Stuns for 3 seconds. (sorry vigilantes, you're gonna need another way to commit your cable cuff citizen's arrest.)
- <strike>The firing pin that accompanies it has only a 60% chance of actually properly firing, and a 40% chance to not fire and give away the intents of the shooter via a log notification that appears for anybody within a 4 tile radius of the shooter. </strike>
  **No, firing pin dumb idea bluh**
## HOW IT'S BALANCED:

Instead of the efficient, NT-branded normal firing pin, this nonlethal weapon has a shitty, homemade firing pin. Because of the pin's shoddy design, it makes any weapon it's installed into have a **40% chance of not firing at all and instead giving a very obvious, loud __click__** upon firing that anybody 4 tiles away from the shooter will notice in their chatlog .
(i.e. _**Traitor McDickface points something at [target], and you hear a click!**_)
In addition to the general unreliability of the pin's firing mechenic, the gun's low stun time and inefficient energy consumption, when the gun actually _does_ fire, it generates sparks (due to the igniter.)
In addition, the homemade firing pin could be used by Science for their fancier, non-shitty science guns in case they can't get standard firing pins. The trade-off however is that Sec will have their asses, and their fancy guns have a chance of not functioning as the schematics indicated they would.

**Please submit feedback, I would very much like to see this item implemented!**

**Comment by Super3222** [comment]
Erm. First of all, I'd like to say be warned. There might be people that'll walk all over this idea. We tried makeshift, craftable gear in the past before and it just didn't go right for a multitude of different reasons.

I sorta like the idea here, but to try to dilute that with the balance within SS13 is going to be hard. I'll be honest with you, because ideas like these don't really get through. I'm sure you know that Yogs really hates powergaming (so basically it's the opposite of /tg/), and the addition of a lot of powerful, shiny ghetto gear opposes that.

Now what I'm getting at is, first you'd have to make this even harder to get.
The recipes not bad, but it's lacking a rare item. Something that'll make it a struggle to craft. Just like how improvised shotguns need a modular receiver.
I'd say change the metal to a few sheets of plasteel, not to take up the spot for a 'rare item'. But letting people get generic metal for crafting a gun is pretty bad.

Another problem, despite how bad the home made firing pin is. It's pretty easy to craft. I'd suggest adding in some more components. Whatever's not /just/ a metal rod.

Homemade firing pins also cannot go inside of more than just this type of gun. I'm sorry, but science is already hilariously overpowered. Making craftable firing pins is out of the question, but I can see an exception if it only works with crappy, ghetto guns like these. This would also be quite literally hell to handle for security when everyone on the station can craft a firing pin at any given time.

Another thing, having a 40% chance at firing not at all is bad nerf. They need a more heavy backfire. Like the blast hitting them in the face and knocking the gun out of their hands. Or just them getting knocked onto the ground and stunned from using it all together.

Something that really makes the gun a gamble. I'd also suggest an overheating mechanism that cannot be drained until the gun backfires ridiculously (like I mentioned in the last para) and, builds up the % amount each time the gun fires (yes i know it has a small amount of charges). Examining the gun will be able to tell you it's stress meter from an accidental charge burst. This'll make it more of a gamble to use, and probably better to balance with in the game.

There will be some people commenting, "NO NO NO NO". Hell, even after my message predicting it, there'll probably still do it. But we've been pretty lenient for a few test merges in the past few weeks, so I don't see why we should exempt this proof of a concept.

That is only implying that we _get past the planning phase_ and into the PR phase.

**Comment by Yewmi** [comment]
@Super3222 
I see. Indeed, I understand the risk of giving the potential for such power to another person.
Actually...!

> Something that really makes the gun a gamble. I'd also suggest an overheating mechanism that cannot be drained until the gun backfires ridiculously

I like the idea you provided for an overheating mechanic. How about the pin giving a 40% chance to _ignite_ the user if they're wearing any clothes on their body?

**Comment by ShadowDeath6** [comment]
>metal gun with a live battery attached to it and a half baked firing pin in it
not making it electrify you on trying to use it

smh fam

anyway if xeno got their hands on a bunch of yellow and metal slimes, which isn't really hard, they can just spam these, provided they have access to enough igniters, which could be problematic considering infinity tasers

**Comment by Kmc2000** [comment]
What's the point of this


You spend all that time making a shit gun, you try to kill someone with it, it shits on you, you are arrested

Taser shots...fuck off, disablers at best

Honestly, i'd have a focusing crystal or something that has a 30 % chance to shatter whenever its fired, so you'd have to replace it.



Even so, ghetto armoury 2.0 anyone?

**Comment by ParagonPrime** [comment]
this is an interesting idea as long as it stays as a _purely defensive_ weapon

that means the stun time should stay low, so all you can use it for is tasering an attacker and running the fuck away

**Comment by EMT321** [comment]
There's already enough issues surrounding improvised shotguns. This is not much better.

-1.

**Comment by AdamElTablawy** [comment]
# craftable tazers

r u serious

even 3 seconds is more than enough to ruin things

hell, soap stuns for ONE second and you're making it count for 3

like

what is the logic behind this idea

all this will do is make revolution end in a sea of furious assistants firing thousands of tazer shots into security hooting like enraged electric chimpanzees 

this is literally ranged stunprods, not to mention a bluespace battery is gonna result in a backpack of six shot tazers

and making CRAFTABLE FIRING PINS????? even with a 40% chance to set the guy on fire he can just heal himself really fast and then science is just going to shit out a thousand laser guns

**Comment by darkwahn** [comment]
I miss the ghetto armory, but feel like a craftable ranged stun might be a bit too strong.

**Comment by ClearedObject** [comment]
I like the concept, stun time needs to go down, or maybe it does some stamina damage instead like a disabler. Craftable firing pins? R&D traitoring just got so much simpler.

**Comment by Yewmi** [comment]
hmm, hmm.
Yeah, in hindsight that firing pin is a bad idea. To be honest, I just added it for the sake of logic, but... yeah, let's remove that pin. Goodness, I wish this site supported strikethrough text.
How about we remove the firing pin entirely AND the taser shot, and instead add a _new_ projectile that fires a standard disabler shot, while still retaining the user-ignition property? A new projectile should be used to differentiate the shots from an actual taser.

**Comment by Cruix** [comment]
<strike>I wish this site supported strikethrough text too, there are many time I would have liked to use it </strike> Yes.

**Comment by Cruix** [comment]
\<strike\> and \<\\strike\> will strikethrough anything between them.

I got them to show up here without the effect with liberal use of \

**Comment by Super3222** [comment]
I like the concept of a gun that's a struggle to use, and quite a gamble to use properly. People might see it as useless, but I see it as a last resort.
