### ISSUE TITLE
Simplify "AI LAW 2 OPEN DOOR REEE"

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#938]
Simple. Ctrl-clicking on an adjacent door as a human allows you to request the AI to open it via a chat popup for the AI.

Speeds things up a bit, I should think.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
would also help with
"AI OPEN MAINT DOOR"
"You are not near any cameras, which door?"
"AI ROGUE BLOW THE BORGS"

**Comment by ParagonPrime** [comment]
^^

**Comment by Super3222** [comment]
That's the stupidest suggestion I've ever read.

**Comment by ParagonPrime** [comment]
your brain is the stupidest thing i've ever heard

i don't have to provide you with a reason because apparently _giving reasons for our stupid fucking criticisms is so passé_

**Comment by ShadowDeath6** [comment]
giving it a cooldown would be necessary but other than that this a pretty good idea, fuck off supr

**Comment by X-TheDark** [comment]
This might really get annoying for AI with some Greytider McShitface & Co. constantly trying to walk into somewhere they don't have access to on a 60 player server. I'm pretty sure the AI has difficulties following the chat as it is.

This would need to be made into a separate Alert window or something.

**Comment by Super3222** [comment]
The fact that this is actually being considered hurts my head.

**Comment by X-TheDark** [comment]
I never deny an idea without having a good argument against it, and I really don't have one for not at least considering this.

**Comment by EMT321** [comment]
This is too easily spammable.

**Comment by utahclock** [comment]
so make it have a cd where u cant spam click for ai ..

**Comment by Super3222** [comment]
Have you people lost your minds

**Comment by ParagonPrime** [comment]
super how about you either shove fifty dicks up your ass or start giving reasons

**Comment by Super3222** [comment]
How about you actually take the effort to type 3-5 words instead of coming here with a half-assed suggestion.

SS13 communication is built like any classic "RP" or whatever game on byond, where you type what you want to say. There might be an exception on Goon, I don't know. Still, sticking to that format is the best thing for the game. You take away that format, and you might as well give people marcos which open up a box letting them say whatever.

This is just too stupid. If you want the AI to listen to your request, just ask it. If they don't respond, just PDA them. Giving "just humans" a marco to send requests to the AI is going to get ignored the same as PDA messages and requests over a radio.

Really, terrible suggestion.

**Comment by ParagonPrime** [comment]
If the door has AI control, I don't think it's too much of a logical leap to assume there's a link in the other direction to let people communicate with the AI via the door itself

and what about holopads? should we remove holopads because they can be abused?

if people deliberately spam it they get boinked. simple as that

**Comment by X-TheDark** [comment]
Not a fan of a feature that might add frustration to admins/AI players.

**Comment by Super3222** [comment]
Holo Pads are designed for "hey Siri" not airlocks. There are already functions in the game for AI players to be right on time to open doors. This suggestion would add nothing more to the game than just a means to annoy the AI.

**Comment by ParagonPrime** [comment]
meh

i don't see how a decently long cooldown wouldn't reduce whatever spam might result

5 seconds ingame time is pretty horrifyingly long; 10 or even 15 would be totally fine

**Comment by AdamElTablawy** [comment]
at this rate we might as well become /tg/ with their fuckig pre-set chat boxes that let you choose commands such as 'help' 'hi'' 'yes'

**Comment by AdamElTablawy** [comment]
also are you, paragonprime, the one guy flapping his dick off about roleplay, seriously suggesting a macro to automatically ask AI to open doors instead of fucking askign them

**Comment by ParagonPrime** [comment]
yes, because it makes _logical sense_ for the station construction teams to equip the airlocks with what is essentially a pimped-up _doorbell_ linked to the ai

but literally anything i say won't convince you so i'm closing this to de-congest my email inbox a bit

**Comment by ShadowDeath6** [comment]
meh, this is an interesting idea, paradise has it and it functions fine, and considering that they're higher RP than us... It just makes the AI need to multitask less since generic dumbass mcshirt #222495 saying """"""""""""""""""""""""""""""""""AI OPIN!!!"""""""""""""""""""""""""""" doesn't require a camera switch onto them. Just QoL things, if you think that this will affect RP you're jaded as fuck.
