### ISSUE TITLE
Changing accents changes for all characters instead of just one.

### ISSUE THREAD

**Issue by Reed0506** [yogstation13/Yogstation#9505]
## Reproduction:
Simple, log on to the server, change an accent, save, and look at your other characters. Their accents will be changed as well.

**Comment by adamsong** [comment]
This is still an issue

**Comment by Hopekz** [comment]
> This is still an issue

This isn't a bug. 

**The reason it was made this way:** 
Silicons don't have personalized character slots so making accents per character would mean that silicons and AI couldn't use accents anymore.

This is a feature atm until someone finds a way around this or decides that silicons can no longer use accents but I've seen AI and cyborgs get enjoyment from using them so that would probably be a weird route to go.

Or maybe making a separate "silicon accent" customization box.

**Comment by adamsong** [comment]
You can configure different silicon names with the different character slots though, so why not different silicon accents?
