### ISSUE TITLE
Super Accelerator breaks if held when Recharge spell is used

### ISSUE THREAD

**Issue by SpaceWarlock** [yogstation13/yogstation#964]
As said in title. As a miner I tried to recharge my charging gun for a double shot. I found the spell in the skeleton shrine area, after I used it the gun essentially stopped working even when dropped or put in bag.

I would pick it up, it would indicate the charge noise, however the gun would still be flashing red and I would get the prompt that the gun is still recharging. This would go on forever.

To reproduce quickly shoot the gun and use the recharge spell, the gun will never charge again.

**Comment by Zostroll** [comment]
This bug also exists in the standard KA's.

**Comment by X-TheDark** [comment]
Now, first of all, this is not actually a bug, but a very nasty (and hilarious) side-effect of how Recharge spell works.

If your equipment uses a power cell (and the KA and derivatives do), the Recharge spell does, in fact, recharge the cell, BUT, there is an 80% chance that the cell gets it's max charge decreased by 200...the problem with KA is that it's cell is 500 charge and that's exactly the cost of reloading it...so, if the Recharge spell decreases the max charge, it will become impossible for the KA to reload itself (since it needs 500, but the cell now holds 300)...this probably needs to be fixed.
