### ISSUE TITLE
Instant Crit from explosion in Lavaland

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#998]
Server Time 2016-10-13 16:50-17:00
Oliver Callison was running next to rock walls and was critted **instantly without any warning at the very moment** when he fired an improved hyper kinetic accelerator at the rock wall at lavaland. No monsters were nearby.

Matskuman5 said there was no sign of any gibtonite explosion in the logs. PDA intact. He ate a legion soul 5 minutes before that, that's all.

![lavaland-death1](https://cloud.githubusercontent.com/assets/16806055/19357251/1a85f93a-9171-11e6-83ca-26d23791635e.png)

**Comment by SeikoTheSeal** [comment]
He fired hyper KA directly at gibonite deposit, which instantly detonates it.

**Comment by 00aquir** [comment]
1. Shouldn't gibtonite flash (even with hyper accelerator) when you fire it? If not, I suggest a change, because not only that it's immediate, but the auto scanner **doesn't even show further minerals** on the screen!

2. No logs? What if a non-traitor throws it at someone else and fires it?

**Comment by AdamElTablawy** [comment]
hyper KA blast at point blank  when not mined makes it insta detonate, so shush



anyway gibtonite explosions don't log when set off on lavaland because it'd be really annoying spam every time a goliath or w/e hits gibtonite, admins wouldn't even bother to check since it happens so commonly and if you gibtonite someone (drag the ore and fire at them to blow thme up) they'll just ahelp

and 00aquir get a dang upgraded autoscanner then

anyway it's point blanking gibtonite that makes it explode, not that its a hyper KA

**Comment by 00aquir** [comment]
Okay thank god if that's the case so then it's ok to shoot it from further away at least, much more manageable with hypers.
