### ISSUE TITLE
Secret borer technique creates two borers, one braindead.

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [yogstation13/yogstation#999]
Title.

**Comment by Super3222** [comment]
Can you explain.

**Comment by ShadowDeath6** [comment]
yfw you don't know the secret borer technique

**Comment by McDonald072** [comment]
Inject a certain reagent into a gold slime core to have a chance to create a borer. In my case both times it happened it created a normal, player controlled borer and one that wanders around doing nothing. 

Now that I think about it, it was probably because I injected 5u while the reaction needs 2u, so it makes 2 borers. Don't know why the second one doesn't have a player assigned, though.

**Comment by ShadowDeath6** [comment]
Reagent count will not do that, probably a fuckup on my part, will check

**Comment by ShadowDeath6** [comment]
tested and reproduced

**Comment by X-TheDark** [comment]
*sigh*

The reason this is happening is because line https://github.com/yogstation13/yogstation/blob/master/code/modules/reagents/chemistry/recipes.dm#L64 spawns the borer that's going to have a player control it, but then the line https://github.com/yogstation13/yogstation/blob/master/code/modules/reagents/chemistry/recipes.dm#L94 spawns the second one, that's not player controlled.
